<ul class="<?= $this->navigation()->menu()->getUlClass() ?>" id="side-menu"> 
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>    
    <?php foreach ($this->container as $page): ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li>
                <a <?php if ($page->isActive()) echo ' class="active"'; ?> href="<?php echo $page->getHref() ?>">
                <?php if (null !== $page->get("icon")): ?>
                    <i class="<?php echo $page->get("icon"); ?>"></i>
                <?php endif; ?>                    
                    <?= $this->translate($page->getLabel()) ?>
                </a>
            </li>
        <?php else: ?>

            <li class="<?php if (hasAcivePages($page)) echo 'active'; ?>">
                <a href="#">
                <?php if (null !== $page->get("icon")): ?>
                    <i class="<?php echo $page->get("icon"); ?>"></i>
                <?php endif; ?>                     
                    <?= $this->translate($page->getLabel()) ?> <span class="fa arrow"></span>
                </a>    
                <ul class="nav nav-second-level">
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                        <li>
                            <a <?php if ($child->isActive()) echo ' class="active"'; ?> href="<?php echo $child->getHref() ?>">
                            <?php if (null !== $child->get("icon")): ?>
                                <i class="<?php echo $child->get("icon"); ?>"></i>
                            <?php endif; ?>                                 
                                <?= $this->translate($child->getLabel()) ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>
<?php
function hasAcivePages($page)
{
    foreach ($page->getPages() as $child) {
        if ($child->isActive())
            return TRUE;
    }
    
    return false;
}