<input type="text" name="recipients"/>
                                              
<?php
$styles = "
    .twitter-typeahead .tt-query,
    .twitter-typeahead .tt-hint {margin-bottom: 0;}
    .twitter-typeahead .tt-hint{display: none;}
    .tt-menu {position: absolute;top: 100%;left: 0;z-index: 1000;display: none;float: left;min-width: 160px;padding: 5px 0;margin: 2px 0 0;list-style: none;font-size: 14px;background-color: #ffffff;border: 1px solid #cccccc;border: 1px solid rgba(0, 0, 0, 0.15);border-radius: 4px;-webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);background-clip: padding-box;cursor: pointer;}
    .tt-suggestion {display: block;padding: 3px 20px;clear: both;font-weight: normal;line-height: 1.428571429;color: #333333;white-space: nowrap;}
    .tt-suggestion:hover,
    .tt-suggestion:focus {color: #ffffff;text-decoration: none;outline: 0;background-color: #428bca;}
";
	
// adding styles
$this->headStyle()->appendStyle($styles);
//bootstrap tagsinput
$this->headLink()->appendStylesheet($this->basePath() . '/js/plugins/bootstrap-tagsinput/src/bootstrap-tagsinput.css', 'all');
$this->headScript()
        ->prependFile($this->basePath() . '/js/plugins/bootstrap-tagsinput/src/typeahead.bundle.min.js')
        ->prependFile($this->basePath() . '/js/plugins/bootstrap-tagsinput/src/bootstrap-tagsinput.js');

//Javascript x campo richiesto
$a = "";
if ($requiredRecipients) {
$a = "
form = elt.closest(\"form\");

form.submit(function(e){
    if (elt.val() == '') {
        alert('Selezionare almeno un destinatario!!');
        e.preventDefault();
    }
});
";
}

//javascript x destinatari di default
$b = "";
if (!empty($defaultValues)) {
    foreach ($defaultValues as $value) {
        $b .= "elt.tagsinput('add', " . \Zend\Json\Json::encode($value, true) . ");" . PHP_EOL;
    }
}

$this->headScript()->appendScript("
$(function() {

var users = new Bloodhound({
  datumTokenizer: Bloodhound.tokenizers.obj.whitespace('text'),
  queryTokenizer: Bloodhound.tokenizers.whitespace,
  prefetch: { 
    ttl: 0,
    url: '/application/index/json-users',
    cache: false
}
  

});
users.initialize();
        
/**
 * Objects as tags
 */
elt = $('input[name=\"recipients\"]');
elt.tagsinput({
  itemValue: 'value',
  itemText: 'text',
  typeaheadjs: {
    name: 'users',
    displayKey: 'value',
    source: users.ttAdapter()
  },
  freeInput: true
});

$b
$a

// HACK: overrule hardcoded display inline-block of typeahead.js
$(\".twitter-typeahead\").css('display', 'inline');
    
    });
");

?>
                                               
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                
                                