<?php

namespace DoctrineORMModule\Proxy\__CG__\Samples\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sample extends \Samples\Entity\Sample implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'customer', 'model', 'qta', 'qtaExpected', 'requestedDeliveryDate', 'paymentTerm', 'standardProduct', 'approvalSample', 'painting', 'toBeSerigraphy', 'voltage', 'plug', 'frequency', 'serigraphy', 'colors', 'cable', 'accessories', 'booklet', 'packaging', 'voltageProvided', 'plugProvided', 'frequencyProvided', 'serigraphyProvided', 'colorsProvided', 'cableProvided', 'accessoriesProvided', 'bookletProvided', 'packagingProvided', 'absorptionProvided', 'pressureProvided', 'sfasamentoProvided', 'edtProvided', 'vpp', 'note', 'noteProvided', 'createdDate', 'editDate', 'email1', 'email2', 'scheduledDeliveryDate', 'currentStatusDate', 'country', 'applicant', 'attachments', 'history', 'status');
        }

        return array('__isInitialized__', 'id', 'customer', 'model', 'qta', 'qtaExpected', 'requestedDeliveryDate', 'paymentTerm', 'standardProduct', 'approvalSample', 'painting', 'toBeSerigraphy', 'voltage', 'plug', 'frequency', 'serigraphy', 'colors', 'cable', 'accessories', 'booklet', 'packaging', 'voltageProvided', 'plugProvided', 'frequencyProvided', 'serigraphyProvided', 'colorsProvided', 'cableProvided', 'accessoriesProvided', 'bookletProvided', 'packagingProvided', 'absorptionProvided', 'pressureProvided', 'sfasamentoProvided', 'edtProvided', 'vpp', 'note', 'noteProvided', 'createdDate', 'editDate', 'email1', 'email2', 'scheduledDeliveryDate', 'currentStatusDate', 'country', 'applicant', 'attachments', 'history', 'status');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Sample $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel($model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($model));

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getQta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQta', array());

        return parent::getQta();
    }

    /**
     * {@inheritDoc}
     */
    public function setQta($qta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQta', array($qta));

        return parent::setQta($qta);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtaExpected()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtaExpected', array());

        return parent::getQtaExpected();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtaExpected($qtaExpected)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtaExpected', array($qtaExpected));

        return parent::setQtaExpected($qtaExpected);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequestedDeliveryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequestedDeliveryDate', array());

        return parent::getRequestedDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequestedDeliveryDate(\DateTime $requestedDeliveryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequestedDeliveryDate', array($requestedDeliveryDate));

        return parent::setRequestedDeliveryDate($requestedDeliveryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerm', array());

        return parent::getPaymentTerm();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerm($paymentTerm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerm', array($paymentTerm));

        return parent::setPaymentTerm($paymentTerm);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoltage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoltage', array());

        return parent::getVoltage();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoltage($voltage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoltage', array($voltage));

        return parent::setVoltage($voltage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlug', array());

        return parent::getPlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlug($plug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlug', array($plug));

        return parent::setPlug($plug);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequency', array());

        return parent::getFrequency();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequency($frequency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequency', array($frequency));

        return parent::setFrequency($frequency);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerigraphy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerigraphy', array());

        return parent::getSerigraphy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerigraphy($serigraphy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerigraphy', array($serigraphy));

        return parent::setSerigraphy($serigraphy);
    }

    /**
     * {@inheritDoc}
     */
    public function getColors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColors', array());

        return parent::getColors();
    }

    /**
     * {@inheritDoc}
     */
    public function setColors($colors)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColors', array($colors));

        return parent::setColors($colors);
    }

    /**
     * {@inheritDoc}
     */
    public function getCable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCable', array());

        return parent::getCable();
    }

    /**
     * {@inheritDoc}
     */
    public function setCable($cable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCable', array($cable));

        return parent::setCable($cable);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessories', array());

        return parent::getAccessories();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessories($accessories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessories', array($accessories));

        return parent::setAccessories($accessories);
    }

    /**
     * {@inheritDoc}
     */
    public function getBooklet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooklet', array());

        return parent::getBooklet();
    }

    /**
     * {@inheritDoc}
     */
    public function setBooklet($booklet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBooklet', array($booklet));

        return parent::setBooklet($booklet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackaging()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackaging', array());

        return parent::getPackaging();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackaging($packaging)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackaging', array($packaging));

        return parent::setPackaging($packaging);
    }

    /**
     * {@inheritDoc}
     */
    public function getVoltageProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVoltageProvided', array());

        return parent::getVoltageProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setVoltageProvided($voltageProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVoltageProvided', array($voltageProvided));

        return parent::setVoltageProvided($voltageProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlugProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlugProvided', array());

        return parent::getPlugProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlugProvided($plugProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlugProvided', array($plugProvided));

        return parent::setPlugProvided($plugProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrequencyProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrequencyProvided', array());

        return parent::getFrequencyProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setFrequencyProvided($frequencyProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFrequencyProvided', array($frequencyProvided));

        return parent::setFrequencyProvided($frequencyProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerigraphyProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerigraphyProvided', array());

        return parent::getSerigraphyProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerigraphyProvided($serigraphyProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerigraphyProvided', array($serigraphyProvided));

        return parent::setSerigraphyProvided($serigraphyProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getColorsProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColorsProvided', array());

        return parent::getColorsProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setColorsProvided($colorsProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColorsProvided', array($colorsProvided));

        return parent::setColorsProvided($colorsProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getCableProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCableProvided', array());

        return parent::getCableProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setCableProvided($cableProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCableProvided', array($cableProvided));

        return parent::setCableProvided($cableProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessoriesProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessoriesProvided', array());

        return parent::getAccessoriesProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessoriesProvided($accessoriesProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessoriesProvided', array($accessoriesProvided));

        return parent::setAccessoriesProvided($accessoriesProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookletProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookletProvided', array());

        return parent::getBookletProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookletProvided($bookletProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookletProvided', array($bookletProvided));

        return parent::setBookletProvided($bookletProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackagingProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackagingProvided', array());

        return parent::getPackagingProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setPackagingProvided($packagingProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackagingProvided', array($packagingProvided));

        return parent::setPackagingProvided($packagingProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsorptionProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsorptionProvided', array());

        return parent::getAbsorptionProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbsorptionProvided($absorptionProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbsorptionProvided', array($absorptionProvided));

        return parent::setAbsorptionProvided($absorptionProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getPressureProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPressureProvided', array());

        return parent::getPressureProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setPressureProvided($pressureProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPressureProvided', array($pressureProvided));

        return parent::setPressureProvided($pressureProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getSfasamentoProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSfasamentoProvided', array());

        return parent::getSfasamentoProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setSfasamentoProvided($sfasamentoProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSfasamentoProvided', array($sfasamentoProvided));

        return parent::setSfasamentoProvided($sfasamentoProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getEdtProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEdtProvided', array());

        return parent::getEdtProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setEdtProvided($edtProvided)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEdtProvided', array($edtProvided));

        return parent::setEdtProvided($edtProvided);
    }

    /**
     * {@inheritDoc}
     */
    public function getStandardProduct($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStandardProduct', array($human));

        return parent::getStandardProduct($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setStandardProduct($standardProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStandardProduct', array($standardProduct));

        return parent::setStandardProduct($standardProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getApprovalSample($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApprovalSample', array($human));

        return parent::getApprovalSample($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setApprovalSample($approvalSample)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApprovalSample', array($approvalSample));

        return parent::setApprovalSample($approvalSample);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail1($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail1', array($human));

        return parent::getEmail1($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail1($email1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail1', array($email1));

        return parent::setEmail1($email1);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail2($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail2', array($human));

        return parent::getEmail2($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail2($email1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail2', array($email1));

        return parent::setEmail2($email1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPainting($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPainting', array($human));

        return parent::getPainting($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setToBeSerigraphy($toBeSerigraphy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToBeSerigraphy', array($toBeSerigraphy));

        return parent::setToBeSerigraphy($toBeSerigraphy);
    }

    /**
     * {@inheritDoc}
     */
    public function getToBeSerigraphy($human = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToBeSerigraphy', array($human));

        return parent::getToBeSerigraphy($human);
    }

    /**
     * {@inheritDoc}
     */
    public function setPainting($painting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPainting', array($painting));

        return parent::setPainting($painting);
    }

    /**
     * {@inheritDoc}
     */
    public function setVpp($vpp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVpp', array($vpp));

        return parent::setVpp($vpp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVpp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVpp', array());

        return parent::getVpp();
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoteProvided()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoteProvided', array());

        return parent::getNoteProvided();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoteProvided($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoteProvided', array($note));

        return parent::setNoteProvided($note);
    }

    /**
     * {@inheritDoc}
     */
    public function setApplicant(\User\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApplicant', array($user));

        return parent::setApplicant($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicant', array());

        return parent::getApplicant();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachments(\Doctrine\Common\Collections\Collection $attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachments', array($attachments));

        return parent::addAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachments(\Doctrine\Common\Collections\Collection $attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachments', array($attachments));

        return parent::removeAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments($type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', array($type));

        return parent::getAttachments($type);
    }

    /**
     * {@inheritDoc}
     */
    public function addHistory(\Doctrine\Common\Collections\Collection $history)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHistory', array($history));

        return parent::addHistory($history);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHistory(\Doctrine\Common\Collections\Collection $history)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHistory', array($history));

        return parent::removeHistory($history);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistory($type = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistory', array($type));

        return parent::getHistory($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessedDate', array());

        return parent::getProcessedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\Samples\Entity\Status $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getScheduledDeliveryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScheduledDeliveryDate', array());

        return parent::getScheduledDeliveryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setScheduledDeliveryDate(\DateTime $scheduledDeliveryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScheduledDeliveryDate', array($scheduledDeliveryDate));

        return parent::setScheduledDeliveryDate($scheduledDeliveryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentStatusDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentStatusDate', array());

        return parent::getCurrentStatusDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentStatusDate(\DateTime $currentStatusDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentStatusDate', array($currentStatusDate));

        return parent::setCurrentStatusDate($currentStatusDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', array());

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(\DateTime $createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', array($createdDate));

        return parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditDate', array());

        return parent::getEditDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditDate(\DateTime $createdDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditDate', array($createdDate));

        return parent::setEditDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\Application\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function isShipped()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isShipped', array());

        return parent::isShipped();
    }

    /**
     * {@inheritDoc}
     */
    public function isProcessed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isProcessed', array());

        return parent::isProcessed();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

}
