<?php
/**
  echo $this->headLink()
  ->appendStylesheet($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css');
  echo $this->headScript()
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.min.js')
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput-angular.js');
 * 
 */
$title = 'Add Category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'create-form');
$form->get('submit')->setValue('Add new category');
$sample = $form->get('category'); //fieldset
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class = "row">
        <div class = "col-md-12">
            <?= $this->ztbFormElement($sample->get('name')); ?>
        </div>    
    </div>
    <div class = "row">
        <div class = "col-md-12">
            <?= $this->ztbFormElement($sample->get('status')); ?>
        </div>    
    </div>

     
    
<div>
    <?= $this->ztbFormElement($form->get('csrf')); ?>
    <?= $this->ztbFormElement($form->get('submit')); ?>
</div>    
<?php 
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {

}); 
");


