<?php echo $this->titleAndBread('Modifica'); ?>
<?php $this->myFlashMessenger(); ?>   
<?php
$status = $proto->getStatus()->getId();
switch ($status) {  
    case 10:
        $class = 'yellow';
        $icon = 'mail-forward';
        break;
    case 15:
        $class = 'yellow';
        $icon = 'hourglass-end';
        break;
    case 20:
        $class = 'primary';
        $icon = 'wrench';
        break;   
    case 25:
        $class = 'primary';
        $icon = 'paint-brush';
        break; 
    case 30:
        $class = 'primary';
        $icon = 'cogs';
        break;  
    case 35:
        $class = 'success';
        $icon = 'check';
        break;     
    case 40:
        $class = 'red';
        $icon = 'trash';
        break;
    default: //5
        $class = 'default';
        $icon = 'clock-o';
        break;
}
?>
<div class="row">
    <div class="col-md-12">

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-<?php echo $class; ?>">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-4">
                        <i class="fa fa-<?php echo $icon; ?> fa-5x"></i>
                    </div>
                    <div class="col-xs-8 text-right">
                        <div class="huge"><?php echo $proto->getStatus()->getName(); ?></div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">
                            <a href="
                            <?php
                            echo $this->url(
                                    'proto/list', ['search_by' => json_encode(['applicant' => $proto->getApplicant()->getId()])]);
                            ?>                                                              
                               ">
                                   <?php echo $proto->getApplicant()->getDisplayName(); ?>
                            </a>    
                        </div>
                    </div>
                </div>
            </div>
        </div>           
    </div>
</div>



<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'edit-form');
$form->get('submit')->setValue('Modifica');
$fieldset = $form->get('proto'); //fieldset
$form->prepare();
$atts = $proto->getAttachments(); //Allegati
$supplies = $proto->getSupplies(); //Forniture
//prendo l'ultima history con stato "Closed" x che mi serve per modificar la data fine
$latestClosedHistory = end($proto->getHistory(\Proto\Entity\Status::STATUS_TYPE_DELIVERED));
echo $this->form()->openTag($form);
echo $this->ztbFormElement($fieldset->get('id'));
?>




<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-lightbulb-o fa-fw"></i> Richiesta: <?= $proto->getId() ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#home" data-toggle="tab">Home</a>
                    </li>
                    <li><a href="#parti" data-toggle="tab"><i class="fa fa-plus fa-fw"></i> Parti</a>
                    </li>
                    <li><a href="#dati-tecnici" data-toggle="tab"><i class="fa fa-th-list fa-fw"></i> Dati Tecnici</a>
                    </li>
                    <li>
                        <a href="#attachments" data-toggle="tab">
                            <i class="fa fa-paperclip fa-fw"></i>
                            Allegati (<?php echo count($atts); ?>)
                        </a>
                    </li>
                    <li>
                        <a href="#supplies" data-toggle="tab">
                            <i class="fa fa-truck fa-fw"></i>
                            Forniture (<?php echo count($supplies); ?>)
                        </a>
                    </li>     
                    <li>
                        <a href="#history" data-toggle="tab">
                            <i class="fa fa-clock-o fa-fw"></i>
                            History
                        </a>
                    </li>                       
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="home">

                        <div class="row">
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('projectCode')); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('type')); ?>
                            </div>                    
                        </div>
                        <div class = "row">
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('family')); ?>
                            </div>     
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('status')); ?>
                            </div>                      
                        </div>   
                        <div class = "row">
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('requestedDeliveryDate')); ?>
                            </div>    
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('expectedDeliveryDate')); ?>
                            </div>                    
                        </div>  
                        <div class = "row">
                            <div class = "col-md-12">
                                <?= $this->ztbFormElement($fieldset->get('destinazioneUso')); ?>
                            </div>      
                        </div>   
                        <div class = "row">
                            <div class = "col-md-12">
                                <?= $this->ztbFormElement($fieldset->get('note')); ?>
                            </div>      
                        </div>                          
                    </div>
                    <div class="tab-pane fade" id="parti">

                        <div class = "row">
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('partiPlastiche')); ?>
                            </div>    
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('partiLavMetallo')); ?>
                            </div>                      
                        </div>
                        <div class = "row">
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('partiTrasparenti')); ?>
                            </div>    
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('partiVerniciate')); ?>
                            </div>                      
                        </div>         
                        <div class = "row">
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('partiGomma')); ?>
                            </div>    
                            <div class = "col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('serigrafie')); ?>
                            </div>                      
                        </div>    
                        <div class = "row">
                            <div class = "col-md-12">
                                <?= $this->ztbFormElement($fieldset->get('partiMatSpeciale')); ?>
                            </div>                         
                        </div>                
                        <div class = "row">
                            <div class = "col-md-12">
                                <?= $this->ztbFormElement($fieldset->get('notePartiMatSpeciale')); ?>
                            </div>      
                        </div>   
                    </div>
                    <div class="tab-pane fade" id="dati-tecnici">
                        <div class="row">
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('tensione')); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('frequenza')); ?>
                            </div>                    
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('potenza')); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('spina')); ?>
                            </div>                    
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('cavo')); ?>
                            </div>
                            <div class="col-md-6">
                                <?= $this->ztbFormElement($fieldset->get('vpp')); ?>
                            </div>                    
                        </div>                        
                        <div class = "row">
                            <div class = "col-md-12">
                                <?= $this->ztbFormElement($fieldset->get('varie')); ?>
                            </div>      
                        </div>  
                    </div>



                    <div class="tab-pane fade" id="attachments">

                        <?php
                        $att['Richiesta'] = $proto->getAttachments(\Proto\Entity\Attachments::ATTACHMENT_TYPE_REQUEST);
                        $att['Evasione'] = $proto->getAttachments(\Proto\Entity\Attachments::ATTACHMENT_TYPE_CLASSIFIED);
                        if ((count($att['Richiesta']) < 1) && (count($att['Evasione']) < 1)):
                            ?>
                            <div class="huge text-center">
                                Nessun allegato presente!
                            </div>
                        <?php else: ?>                
                            <?php foreach ($att as $key => $value): ?>
                                <?php if (!count($value) < 1): ?>                
                                    <div class="table-responsive">
                                        <table class="table">
                                            <tr>
                                                <th colspan="4"><?= $key ?></th>
                                            </tr>
                                            <?php foreach ($value as $attachment): ?>                        
                                                <tr>
                                                    <td class="col-md-2">
                                                        <a 
                                                        <?php if ($attachment->isImage()): ?>
                                                                class="fancybox-thumb" rel="fancybox-thumb"
                                                            <?php endif; ?>                                                 

                                                            target="_blank" href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                                                            <img class="img-responsive" style="max-height: 30px" src="/img/file-extension/<?php echo $attachment->getIcon(); ?>" alt="<?php echo $attachment->getFileName(); ?>" />
                                                        </a>
                                                    </td>
                                                    <td class="col-md-6">
                                                        <a target="_blank" href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                                                            <?php echo $attachment->getFileName(); ?>
                                                        </a>
                                                    </td>
                                                    <td class="col-md-4">
                                                        <?php
                                                        echo $this->dateFormat(
                                                                $attachment->getCreatedDate(), IntlDateFormatter::LONG, // date
                                                                IntlDateFormatter::NONE, // time
                                                                "it_IT");
                                                        ?>
                                                    </td>   
                                                    <td>
                                                        <a href="<?php echo $this->url('proto/attachments/remove', array('attachmentId' => $attachment->getId())); ?>"
                                                           class="btn btn-danger btn-xs emodal-confirm">
                                                            <span class="glyphicon glyphicon-remove"></span> Del
                                                        </a>                                          
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>                         
                                        </table>
                                    </div>
                                <?php endif; ?>    
                            <?php endforeach; ?>                
                        <?php endif; ?>                
                        <div class="huge text-center" style="margin-top: 30px">
                            <a href="<?php echo $this->url('proto/attachments/add', array('entity_id' => $proto->getId(), 'type' => 'evasione')); ?>" class="btn btn-primary btn-lg">
                                <i class="fa fa-paperclip fa-fw"></i> Aggiungi allegati
                            </a>
                        </div>
                    </div><!-- /Allegati -->



                    <div class="tab-pane fade" id="supplies" style="padding-top: 20px">

                        <?php if ((count($supplies)) < 1): ?>
                            <div class="huge text-center">
                                Nessuna fornitura presente!
                            </div>
                        <?php else: ?>                
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th>ID</th>
                                        <th>Fornitore</th>
                                        <th>N° Ordine</th>
                                        <th>Data fornitura</th>
                                        <th><i class="fa fa-paperclip"></i></th>
                                        <th></th>
                                    </tr>
                                    <?php foreach ($supplies as $supply): ?>                        
                                        <tr>
                                            <td>
                                                <a href="<?php echo $this->url('proto/supplies/edit', array('supplyId' => $supply->getId())); ?>"><?php echo $supply->getId(); ?></a>
                                            </td>
                                            <td>
                                                <?php echo $supply->getSupplier()->getCompanyName(); ?>
                                            </td>
                                            <td>
                                                <?php echo $supply->getOrderNr(); ?>
                                            </td>                                            
                                            <td>
                                                <?php
                                                echo $this->dateFormat(
                                                        $supply->getSupplyDate(), IntlDateFormatter::LONG, // date
                                                        IntlDateFormatter::NONE, // time
                                                        "it_IT");
                                                ?>
                                            </td>   
                                            <td>
                                                <a href="/proto/supplies/attachments/<?php echo $supply->getId(); ?>" data-toggle="modal" data-target="#myModal" data-remote="false">
                                                    <?= count($supply->getAttachments()); ?>
                                                </a>
                                            </td>                                            
                                            <td class="cell cell-ctrls text-center">
                                                <div class="btn-group">
                                                    <a href="<?php echo $this->url('proto/attachments/add', array('entity_id' => $supply->getId(), 'type' => 'fornitura')); ?>"
                                                       class="btn btn-warning btn-xs">
                                                        <span class="fa fa-paperclip"></span> Allega
                                                    </a>                                                       
                                                    <a href="<?php echo $this->url('proto/supplies/edit', array('supplyId' => $supply->getId())); ?>"
                                                       class="btn btn-info btn-xs">
                                                        <span class="fa fa-edit"></span> Edit
                                                    </a>                                                  
                                                    <a href="<?php echo $this->url('proto/supplies/remove', array('supplyId' => $supply->getId())); ?>"
                                                       class="btn btn-danger btn-xs emodal-confirm">
                                                        <span class="fa fa-trash"></span> Del
                                                    </a>      
                                                </div>                        

                                            </td>    

                                        </tr>
                                    <?php endforeach; ?>                         
                                </table>
                            </div>


                        <?php endif; ?>                
                        <div class="huge text-center" style="margin-top: 30px">
                            <a href="<?php echo $this->url('proto/supplies/add', array('proto_id' => $proto->getId())); ?>" class="btn btn-primary btn-lg">
                                <i class="fa fa-truck fa-fw"></i> Aggiungi fornitura
                            </a>
                        </div>
                    </div><!-- /Forniture -->                    

                    <div class="tab-pane fade" id="history" style="padding-top: 20px">

                        
                <ul class="timeline">
                    <?php
                    $count = 0;
                    $history = $proto->getHistory();
                    foreach ($history as $row):
                        $count++;
                        $timelineClass = (($count % 2) == 0) ? 'timeline-inverted' : '';
                        ?>
                        <li class="<?php echo $timelineClass; ?>">
                            <div class="timeline-badge <?php echo $row->getAttributes()['class']; ?>"><i class="fa <?php echo $row->getAttributes()['icon']; ?>"></i>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="timeline-title"><?php echo $row->getProtoStatus()->getName(); ?></h4>
                                    <p>
                                        <small class="text-muted"><i class="fa fa-clock-o"></i> <?php
                                            echo $this->dateFormat(
                                                    $row->getEditDate(), IntlDateFormatter::LONG, // date
                                                    IntlDateFormatter::SHORT, // time
                                                    "it_IT");
                                            ?>
                                        </small>
                                    </p>
                                    <p>
                                        <small class="text-muted">
                                            <i class="fa fa-user"></i>
                                            <?php echo $row->getEditBy()->getDisplayName(); ?>
                                        </small>
                                    </p>  
                                </div>
                                <div class="timeline-body">
                                    <p></p>
                                </div>
                            </div>
                        </li>                    
<?php endforeach; ?>                    


                </ul>                        
                        
                        
   
                    </div><!-- /history -->    


                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>                


<div class="row">
    <div class="col-md-12 text-right">
        <p>
            <button class="btn btn-primary btn-lg" type="submit"><i class="fa fa-edit"></i> Modifica</button>
            <a href="<?php echo $this->url('proto/remove', array('protoId' => $proto->getId())); ?>"
               class="btn btn-danger btn-lg emodal-confirm">
                <i class="fa fa-trash"></i> Elimina
            </a>      
            <a class='btn btn-default btn-lg' href="<?php echo $this->url('proto/print', array('protoId' => $proto->getId())); ?>">
                <i class="fa fa-print"></i> Stampa
            </a>                                     
            <a class="btn btn-default btn-lg" href="<?php echo $this->url('proto/list') ?>"><i class="fa fa-mail-reply"></i> Annulla</a>
        </p>
    </div>
</div>













<!-- Default bootstrap modal example -->
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Allegati fornitura</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>




<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/timeline.css', 'all');
//fancyBox
$this->headLink()
        ->appendStylesheet($this->basePath() . '/js/plugins/fancyBox/source/helpers/jquery.fancybox-thumbs.css', 'all')
        ->appendStylesheet($this->basePath() . '/js/plugins/fancyBox/source/jquery.fancybox.css', 'all');
$this->headScript()
        ->prependFile($this->basePath() . '/js/plugins/fancyBox/source/helpers/jquery.fancybox-thumbs.js')
        ->prependFile($this->basePath() . '/js/plugins/fancyBox/source/jquery.fancybox.js');


$this->headScript()->appendScript("
$(function() {

	$('.fancybox-thumb').fancybox({
		prevEffect	: 'none',
		nextEffect	: 'none',
		helpers	: {
			title	: {
				type: 'outside'
			},
			thumbs	: {
				width	: 50,
				height	: 50
			}
		}
	});
        
        //Modifico sorgente thumb (altrimente mi prende l'icona dell'estensione)
        $('.fancybox-thumb').fancybox({
            helpers : {
                thumbs : {
                    source: function( item ) {
                        return item.href;
                     }
                }
            }
        });
        

// Fill modal with content from link href
$(\"#myModal\").on(\"show.bs.modal\", function(e) {
    var link = $(e.relatedTarget);
    $(this).find(\".modal-body\").load(link.attr(\"href\"));
});


    
    });
");
