<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZfcAdmin - Zend Framework 2 Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('zfcadmin') ?>">My ZfcAdmin</a>
                </div>               

                <div class="collapse navbar-collapse">                              
                    <?php
                    echo $this->navigation('my_admin_navigation')
                            ->menu()
                            ->setUlClass('nav navbar-nav')
                            ->setMaxDepth(1)
                            ->setPartial(array('partial/topnav.phtml', 'Admin'))
                            ->setRenderInvisible(true)
                    ?>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->zfcUserDisplayName(); ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Sign Out'); ?></a></li>
                            </ul>
                        </li>
                    </ul>                           

                </div>

            </div>
        </nav>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>








