<?php echo $this->titleAndBread('Aggiungi Fornitura'); ?>
<?php $this->myFlashMessenger(); ?>    

<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Aggiungi fornitura alla richiesta
            </div>
            <div class="panel-body">
                <h4>
                    Richiesta: 
                    <a href="<?php echo $this->url('proto/show', array('protoId' => $proto->getId())); ?>">
                        <?php echo $proto->getId(); ?>
                    </a>                    
                </h4> 
                <?= $this->ztbFormElement($form->get('supplier')); ?>
                <?= $this->ztbFormElement($form->get('orderNr')); ?>
                <?= $this->ztbFormElement($form->get('supplyDate')); ?>
                <?= $this->ztbFormElement($form->get('proto')); ?>
            </div>    
        </div>
    </div>    
</div>     
<div class="row">
    <div class = "col-md-6">
        
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Aggiungi Fornitura</button>
            <a class="btn btn-default" href="<?php echo $this->url('proto/edit', array('protoId' => $proto->getId())); ?>"><i class="fa fa-mail-reply"></i> Annulla</a>
            <a class="btn btn-default" href="<?php echo $this->url('application/suppliers/list'); ?>">Gestione Fornitori</a>
        </div>
    </div>        

    </div>
</div>  
