<?php echo $this->titleAndBread('Allegati fornitura'); ?>
<?php $this->myFlashMessenger(); ?>    
<div class="row">
    <div class="col-md-12">                
        Trovati <?php echo count($rows); ?> allegati
    </div>
</div>  

        
<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                </th>
                <th>
                    File Name
                </th>    
                <th class="text-center"><i class="fa fa-calendar fa-fw"></i></th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($rows as $attachment): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $attachment->getId(); ?>
                    </td>
                    <td class="cell">
                        <a target="_blank" href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                            <img class="img-responsive" style="max-height: 30px" src="/img/file-extension/<?php echo $attachment->getIcon(); ?>" alt="<?php echo $attachment->getFileName(); ?>" />
                        </a>
                    </td>                     
                    <td class="cell cell-serial">
                        <a target="_blank" href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                            <?php echo $attachment->getFileName(); ?>
                        </a>
                    </td>           
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $attachment->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>                      
                    <td class="cell cell-ctrls text-center">
                        <?php if ($this->isEditor): ?> 
                        <a href="<?php echo $this->url('proto/attachments/remove', array('attachmentId' => $attachment->getId())); ?>"
                           class="btn btn-danger btn-xs emodal-confirm">
                            <span class="glyphicon glyphicon-remove"></span> Del
                        </a>
                        <?php endif; ?>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
