<?php echo $this->titleAndBread('Modifica fornitura'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'edit-form');
$form->get('submit')->setValue('Modifica storico');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Modifica fornitura
            </div>
            <div class="panel-body">
                <h4>
                    Richiesta: 
                    <a href="<?php echo $this->url('proto/show', array('protoId' => $proto->getId())); ?>">
                        <?php echo $proto->getId(); ?>
                    </a>                    
                </h4> 
                <?= $this->ztbFormElement($form->get('supplier')); ?>
                <?= $this->ztbFormElement($form->get('orderNr')); ?>
                <?= $this->ztbFormElement($form->get('supplyDate')); ?>
                <?= $this->ztbFormElement($form->get('proto')); ?>
                
            </div>    
        </div>
    </div>    
</div>     
<div class="row">
    <div class = "col-md-6">
            <button class="btn btn-primary">Modifica Fornitura</button>
            <a class="btn btn-default" href="<?php echo $this->url('proto/edit', array('protoId' => $proto->getId())); ?>"><i class="fa fa-mail-reply"></i> Annulla</a>
    </div>
</div>    
<?php
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {

}); 
");


