<?php echo $this->titleAndBread('Edit Brand'); ?>
<?php $this->myFlashMessenger(); ?>    

<div class="panel panel-default">
    <div class="panel-body">
        <a href="<?php echo $this->url('computer/brand/create') ?>" class="btn btn-primary">
            <?php echo $this->translate('Aggiungi nuovo brand') ?>
        </a>
    </div>
</div>

<div class="table">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Stato</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->brands as $brand): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $brand->getId(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $brand->getName(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $brand->getStatus(); ?>
                    </td>                                      
                    <td class="cell cell-ctrls">
                        <a href="<?php echo $this->url('computer/brand/edit', array('brandId' => $brand->getId())); ?>">
                            <?php echo $this->translate('Edit') ?>
                        </a>
                        |
                        <a href="<?php echo $this->url('computer/brand/remove', array('brandId' => $brand->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete brand?') ?>')">
                               <?php echo $this->translate('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->brands, 'Sliding', 'paginator-slide', array(
    'order_by' => 'id',
    'order' => 'ASC',
    'search_by' => NULL,
    'pageAction' => $pageAction,
        )
);
?>


<?php
/* DataTables */
$this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/datatables/dataTables.bootstrap.css');

$this->headScript()
        ->appendFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.js')
        ->appendFile($this->basePath() . '/js/plugins/datatables/dataTables.bootstrap.js');

$this->inlineScript()->captureStart();
echo <<<JS
    $("#example1").dataTable();
JS;
$this->inlineScript()->captureEnd();
?>  