<?php if (!$isAjax): ?>
<?php echo $this->titleAndBread('Campionatura spedita'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php endif; ?>
<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'edit-form');
$form->get('submit')->setValue('Imposta come spedita');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class = "col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <i class="fa fa-plane"></i> Imposta la campionatura come spedita
            </div>
            <div class="panel-body">
                <h4>
                    Campionatura: 
                    <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                        <?php echo $sample->getId(); ?>
                    </a>                    
                </h4> 
                <?= $this->ztbFormElement($form->get('sampleStatus')); ?>
                <?= $this->ztbFormElement($form->get('editDate')); ?>
            </div>    
        </div>
    </div>    
</div>     
<div class="row">
    <div class = "col-md-6">
        <?= $this->ztbFormElement($form->get('editBy')); ?>
        <?= $this->ztbFormElement($form->get('sample')); ?>
        <button class="btn btn-success">Spedisci</button>
        <?php if (!$isAjax): ?>
        <a class="btn btn-default" href="javascript: window.history.back();" id="zzz">Annulla</a>
        <?php endif; ?>
    </div>
</div>    
<?php
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {
}); 
");
