<h3>Richiesta:</h3>
<strong>Id:</strong> <?= $proto->getId() . '<br/>'; ?>
<strong>Richiedente:</strong> <?= $proto->getApplicant()->getDisplayName() . '<br/>'; ?>
<strong>Codice progetto:</strong> <?= $proto->getProjectCode() . '<br/>'; ?>
<strong>Famiglia:</strong> <?= $proto->getFamily()->getName() . '<br/>'; ?>
<strong>Destinazione uso:</strong> <?= nl2br($proto->getDestinazioneUso()) . '<br/>'; ?>

<p>
    Vai alla <a href="<?= $url ?>">richiesta</a>
</p>