<?php echo $this->titleAndBread('Richiedi Campionatura'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/plugins/bootstrap-select/css/bootstrap-select.min.css', 'all')
        //datepicker
        ->appendStylesheet($this->basePath() . '/js/plugins/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css', 'all');
$this->headScript()
        ->prependFile($this->basePath() . '/css/plugins/bootstrap-select/js/bootstrap-select.min.js')
        //datepicker
        ->prependFile($this->basePath() . '/js/plugins/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js')
        ->prependFile($this->basePath() . '/js/plugins/moment-js/moment-with-locales.js');
?>

<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'create-form');
$form->get('submit')->setValue('Richiedi campionatura');
$sample = $form->get('sample'); //fieldset
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class = "row">
    <div class = "col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Richiesta
            </div>
            <div class="panel-body">
                <div class = "row">
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('customer')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('country')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('model')); ?>
                    </div>    
                </div>
                <div class = "row">
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('qta')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('qtaExpected')); ?>
                    </div>
                    <div class = "col-md-4">
       
                        <div class="control-group">
                            <label for="datetimepicker2">Data consegna richiesta</label>
                            <div class='input-group date'  id="datetimepicker2">
                                <?= $this->formElement($sample->get('requestedDeliveryDate')); ?>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>


                       
                        
                        
                        <?php //echo $this->ztbFormElement($sample->get('requestedDeliveryDate')); ?>
                    </div>    
                </div>
                <div class = "row">
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('paymentTerm')); ?>
                    </div>   
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('standardProduct')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('approvalSample')); ?>
                    </div>    
                </div>   
            </div>    
        </div>
    </div>      
</div>

<div class = "row">
    <div class = "col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Dati tecnici
            </div>
            <div class="panel-body">
                <div class = "row">
                    <div class = "col-md-6">
                        <?= $this->ztbFormElement($sample->get('voltage')); ?>
                    </div>   
                    <div class = "col-md-6">
                        <?= $this->ztbFormElement($sample->get('frequency')); ?>
                    </div> 
                </div>    
                <div class = "row">
                    <div class = "col-md-6">
                        <?= $this->ztbFormElement($sample->get('plug')); ?>
                    </div>   
                    <div class = "col-md-6">
                        <?= $this->ztbFormElement($sample->get('cable')); ?>
                    </div> 
                </div>  
                <div class = "row">
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('serigraphy')); ?>
                    </div>   
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('colors')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('accessories')); ?>
                    </div>    
                </div> 
                <div class = "row">
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('vpp')); ?>
                    </div>   
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('booklet')); ?>
                    </div>
                    <div class = "col-md-4">
                        <?= $this->ztbFormElement($sample->get('packaging')); ?>
                    </div>    
                </div>     
            </div>    
        </div>
    </div>      
</div>





<div class = "row">
    <div class = "col-md-12">
        <?= $this->ztbFormElement($sample->get('note')); ?>
    </div>      
</div>       

<div>
    <?= $this->ztbFormElement($sample->get('applicant')); ?>
    <?= $this->ztbFormElement($sample->get('status')); ?>
    <?= $this->ztbFormElement($form->get('submit')); ?>
</div>    
<?php
echo $this->form()->closeTag();
?>

<?php
if (!$isPost) {
    $check = "$('#standardProduct').prop('checked', true);";
} else {
    $check = '';
}
$this->headScript()->appendScript("
$(function() {

    $('#datetimepicker2').datetimepicker({
        format: 'YYYY-MM-DD',
        showTodayButton: true,
        minDate: '" . date('Y-m-d') . "',
        locale: 'en'
    });

    //$('#standardProduct').prop('checked', true);
    //defaultValue();
    $check
    defaultValue();

    $('#standardProduct').change(function() {
        defaultValue();
    }); 
    

    function defaultValue () {
       var defaultValue = 'Standard';
       console.log('ok');

        if($('#standardProduct').is(\":checked\")) {
            $('#voltage, #serigraphy, #frequency, #plug, #cable, #colors, #accessories, #booklet, #packaging').val(defaultValue).attr('readonly', true);
            $('#vpp').val('//').attr('readonly', true);
        } else {
            $('#voltage, #serigraphy, #frequency, #plug, #cable, #colors, #accessories, #vpp, #booklet, #packaging').attr('readonly', false);
        }    
    }
    
}); 

");
