<?php echo $this->titleAndBread('Campionature'); ?>
<?php $this->myFlashMessenger(); ?>   

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-cubes fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php
                                                echo $this->numberFormat(
                                                        $sampleCount, NumberFormatter::DEFAULT_STYLE, NumberFormatter::TYPE_DEFAULT, "it_IT"
                                                );
                                                ?></div>
                        <div>Campionatuer presenti!</div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('samples/list'); ?>">
                <div class="panel-footer">
                    <span class="pull-left">Mostra Tutte</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>



</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-pencil"></i> Ultimi inserimenti
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table class="table table-bordered table-hover" id="example1">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Modello</th>
                            <th>Cliente</th>    
                            <th>Richiedente</th>
                            <th>Stato</th>
                            <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>
                            <th class="text-center"><i class="fa fa-calendar fa-fw"></i></th>
                            <th>Action</th>
                        </tr>
                    </thead>    
                    <?php foreach ($this->samples as $sample): ?>
                        <?php
                        $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());
                        ?>
                        <tr class="<?= $class; ?>">
                            <td class="cell cell-id">
                                <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                                    <?php echo $sample->getId(); ?>
                                </a>
                            </td>
                            <td class="cell cell-serial">
                                <?php echo $sample->getModel(); ?>
                            </td>         
                            <td class="cell">
                                <?php echo $sample->getCustomer(); ?>
                            </td>       
                            <td class="cell">
                                <a href="/samples/list/search_by/%7B%22search%22:%22<?php echo $sample->getApplicant()->getDisplayName(); ?>%22%7D">
                                    <?php echo $sample->getApplicant()->getDisplayName(); ?>
                                </a>
                            </td>    
                            <td class="cell">
                                <a href="/samples/list/search_by/%7B%22search%22:%22<?php echo $sample->getStatus()->getName(); ?>%22%7D">
                                    <?php echo $sample->getStatus()->getName(); ?>
                                </a>    
                            </td>    
                            <td class="cell text-center">
                                <?php echo count($sample->getAttachments()); ?>
                            </td>   
                            <td class="cell text-center">
                                <?php
                                echo $this->dateFormat(
                                        $sample->getCreatedDate(), IntlDateFormatter::LONG, // date
                                        IntlDateFormatter::NONE, // time
                                        "it_IT");
                                ?>                        
                            </td>                      
                            <td class="cell cell-ctrls text-center">
                                <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                                    <span class="glyphicon glyphicon-eye-open"></span> Show
                                </a>                         
                            </td>

                        </tr>
                    <?php endforeach; ?>    

                </table>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

    
    
<hr>
<h1>Statistiche</h1>
<hr>

<div class="row">    
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-pie-chart"></i> All time
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-status"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-pie-chart"></i> <?= date('Y') ?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="flot-chart">
                    <div class="flot-chart-content" id="flot-pie-status-y"></div>
                </div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->


</div>




<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart"></i> Campionature per anno
            </div>
            <!-- /.panel-heading -->

            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Anno</th>
                                        <th>Campionature</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($chartStatCountByYear as $item): ?>
                                        <tr>
                                            <td><?= $item['y']; ?></td>
                                            <td><?php
                                                echo $this->numberFormat(
                                                        $item['nr'], NumberFormatter::DEFAULT_STYLE, NumberFormatter::TYPE_DEFAULT, "it_IT"
                                                );
                                                ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.col-lg-4 (nested) -->
                    <div class="col-lg-8">
                        <div id="morris-bar-chart"></div>
                    </div>
                    <!-- /.col-lg-8 (nested) -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
</div>


<!-- Flot Charts JavaScript --> 
<?php
$this->headScript()
        //->prependFile($this->basePath() . '/js/plugins/flot/flot-data.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.tooltip.min.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.resize.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.pie.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/excanvas.min.js')
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js');

$this->headLink()->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css', 'all');

$pieStatusData = '';
foreach ($chartPieStatus as $item) {
    $pieStatusData .= '{label: "' . $item['name'] . '",data: ' . $item['nr'] . '}, ' . PHP_EOL;
}

$pieStatusYData = '';
foreach ($chartPieStatusY as $item) {
    $pieStatusYData .= '{label: "' . $item['name'] . '",data: ' . $item['nr'] . '}, ' . PHP_EOL;
}

$chartStatCountByYearData = '';
foreach ($chartStatCountByYear as $item) {
    $chartStatCountByYearData .= '{y: "' . $item['y'] . '",a: ' . $item['nr'] . '}, ' . PHP_EOL;
}

$this->headScript()->appendScript("
$(function() {
//Flot Pie Chart


    //Status
    var dataStatus = [" . $pieStatusData . "];
    var plotObj = $.plot($(\"#flot-pie-status\"), dataStatus, {
        colors: [\"#f5f5f5\", \"#edc240\",\"#5bc0de\",\"#5cb85c\", \"green\",\"#d9534f\"],
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: \"%p.0%, %s\", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });
    
    //StatusY
    var dataStatusY = [" . $pieStatusYData . "];
    var plotObj = $.plot($(\"#flot-pie-status-y\"), dataStatusY, {
        colors: [\"#f5f5f5\", \"#edc240\",\"#5bc0de\",\"#5cb85c\", \"green\",\"#d9534f\"],
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: \"%p.0%, %s\", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });



    var data2 = [" . $chartStatCountByYearData . "];
    Morris.Bar({
        element: 'morris-bar-chart',
        data: data2,
        xkey: 'y',
        ykeys: ['a'],
        labels: ['Campionature'],
        hideHover: 'auto',
        resize: true
    });

}); 

");
