<?php 
echo $this->titleAndBread('Campionature');
$this->myFlashMessenger(); 

$this->headLink()
        ->appendStylesheet($this->basePath() . '/css/plugins/bootstrap-select/css/bootstrap-select.min.css', 'all');
$this->headScript()
        ->prependFile($this->basePath() . '/css/plugins/bootstrap-select/js/bootstrap-select.min.js');
?>
<?php
$url_order = 'ASC';
if ($order_by == 'id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'customer') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'model') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}
?>
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                <strong>Trovate <?php echo $totalRecord; ?> campionature</strong>
            </div>
            <div class="col-md-6 right" style="text-align: right">
                <a href="<?php echo $this->url('samples/create') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Richiedi nuova campionatura') ?>
                </a>           
            </div>
        </div>
    </div>
</div>

<style>
    label {margin-right: 5px}
    .bootstrap-select  {width: 200px!important}
</style>

<div class="panel panel-default">
                <div class="panel-heading">
                <i class="fa fa-search"></i> Ricerca Campionature
            </div>
    <div class="panel-body">        
        <div class="row">

            <div class="col-md-12">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('samples/search'));
                $form->setAttribute('class', 'form-inline');
                $form->prepare();

                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <?php
                    echo $this->formRow($form->get('id')->setAttribute('style', 'margin-right: 10px'));
                    echo $this->formRow($form->get('model')->setAttribute('style', 'margin-right: 10px'));
                    echo $this->formRow($form->get('customer')->setAttribute('style', 'margin-right: 10px'));
                    echo $this->formRow($form->get('status')->setAttribute('style', 'margin-right: 10px'));
                    echo $this->formRow($form->get('applicant')->setAttribute('style', 'margin-right: 10px'));
                    ?>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Trova</button>
                    <?php if($showResetBtn): ?>
                    <a class="btn btn-default" href="<?= $this->url('samples/list'); ?>"><i class="fa fa-eraser"></i> Reset</a>
                    <?php endif; ?>
                </div>
                <?php
                echo $this->form()->closeTag();
                ?>                 
            </div>

        </div>
    </div>
</div>


<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'id', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Id
                    </a> 
                    <?php if ($order_by == 'id'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'model', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Modello
                    </a> 
                    <?php if ($order_by == 'model'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'customer', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Cliente
                    </a> 
                    <?php if ($order_by == 'customer'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>    
                <th>Richiedente</th>
                <th>Stato</th>
                <th class="text-center">Data stato corrente</th>
                <th class="text-center">Data richiesta</th>
                <th class="text-center">Qta</th>
                <th class="text-center">Data consegna richiesta</th>
                <th class="text-center">Data consegna prevista</th>
                <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>                
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->samples as $sample): ?>
                <?php
                $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());
                ?>
                <tr class="<?= $class; ?>">
                    <td class="cell cell-id">
                        <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <?php echo $sample->getId(); ?>
                        </a>    
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $sample->getModel(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $sample->getCustomer(); ?>
                    </td>       
                    <td class="cell">
                        <a href="
                        <?php
                        echo $this->url(
                                'samples/list', ['search_by' => json_encode(['applicant' => $sample->getApplicant()->getId()])]);
                        ?>
                           ">                      
    <?php echo $sample->getApplicant()->getDisplayName(); ?>
                        </a>
                    </td>    
                    <td class="cell">
                        <a href="
                        <?php
                        echo $this->url(
                                'samples/list', ['search_by' => json_encode(['status' => $sample->getStatus()->getId()])]);
                        ?>                           
                           ">
    <?php echo $sample->getStatus()->getName(); ?>
                        </a>    
                    </td>  
                    <td class="cell text-center">
                        <?php
                        if (!empty($sample->getCurrentStatusDate())) {
                            echo $this->dateFormat(
                                $sample->getCurrentStatusDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        }
                        ?>                        
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>         
                    <td class="cell text-center">
                        <?php echo $sample->getQta(); ?>
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>      
                    <td class="cell text-center">
                        <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                            <?php
                            echo $this->dateFormat(
                                    $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                    IntlDateFormatter::NONE, // time
                                    "it_IT");
                            ?>       
                        <?php endif; ?>
                    </td>  
                    <td class="cell text-center">
    <?php echo count($sample->getAttachments()); ?>
                    </td>                      
                    <td class="cell cell-ctrls text-center">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                    </td>

                </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->samples, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);
