<?php echo $this->titleAndBread('Campionature'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
$url_order = 'ASC';
if ($order_by == 'id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'customer') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'model') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}
?>
<div class="row">
    <div class="col-md-12">                
        Trovate <?php echo $totalRecord; ?> campionature
    </div>
</div>   
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                <a href="<?php echo $this->url('samples/create') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Richiedi nuova campionatura') ?>
                </a>
            </div>
            <div class="col-md-6">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('samples/search'));
                $form->setAttribute('class', 'navbar-form navbar-right');
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formSearch($form->get('search'));
                echo $this->formButton()->render($form->get('submit'), 'Go!');

                echo $this->form()->closeTag();
                ?>               
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'id', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Id
                    </a> 
                    <?php if ($order_by == 'id'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'model', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Modello
                    </a> 
                    <?php if ($order_by == 'model'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/list', array_filter(array('order_by' => 'customer', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Cliente
                    </a> 
                    <?php if ($order_by == 'customer'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>    
                <th>Richiedente</th>
                <th>Stato</th>
                <th class="text-center"><i class="fa fa-calendar fa-fw"></i></th>
                <th class="text-center">Qta</th>
                <th class="text-center">Data consegna richiesta</th>
                <th class="text-center">Data consegna prevista</th>
                <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>                
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->samples as $sample): ?>
            <?php
            $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());   
            ?>
                <tr class="<?= $class; ?>">
                    <td class="cell cell-id">
                        <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <?php echo $sample->getId(); ?>
                        </a>    
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $sample->getModel(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $sample->getCustomer(); ?>
                    </td>       
                    <td class="cell">
                        <a href="
                            <?php echo $this->url(
                                'samples/list', 
                                ['search_by' => json_encode(['search' => $sample->getApplicant()->getDisplayName()])]); ?>
                           ">                      
                        <?php echo $sample->getApplicant()->getDisplayName(); ?>
                        </a>
                    </td>    
                    <td class="cell">
                        <a href="
                            <?php echo $this->url(
                                'samples/list', 
                                ['search_by' => json_encode(['search' => $sample->getStatus()->getName()])]); ?>                           
                           ">
                        <?php echo $sample->getStatus()->getName(); ?>
                        </a>    
                    </td>     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>         
                    <td class="cell text-center">
                        <?php echo  $sample->getQta(); ?>
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>      
                    <td class="cell text-center">
                        <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                        <?php
                        echo $this->dateFormat(
                                $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>       
                        <?php endif; ?>
                    </td>  
                    <td class="cell text-center">
                        <?php echo  count($sample->getAttachments()); ?>
                    </td>                      
                    <td class="cell cell-ctrls text-center">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->samples, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);


$this->url(
        'samples/search', 
        [], 
        [
            'query' =>['search_by' => json_encode($sample->getApplicant()->getDisplayName())]
        ]);