<?php echo $this->titleAndBread('Campionature Aperte di ' . $user->getDisplayName()); ?>
<?php $this->myFlashMessenger(); ?>    

<!-- Lista campionature -->
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                Trovate <strong><?php echo $totalRecord; ?></strong> campionature aperte
            </div>
            <div class="col-md-6 right " style="text-align: right">
                <a href="<?php echo $this->url('samples/list') ?>" class="btn btn-primary">
                    Elenco completo
                </a>                            
            </div>
        </div>
    </div>
</div>


    <div class="">
        <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Modello</th>
                <th>Cliente</th>    
                <th>Richiedente</th>
                <th>Stato</th>
                <th class="text-center">Data stato corrente</th>
                <th class="text-center">Data richiesta</th>
                <th class="text-center">Qta</th>
                <th class="text-center">Data consegna richiesta</th>
                <th class="text-center">Data consegna prevista</th>
                <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>                
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->samples as $sample): ?>
                <?php
                $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());
                ?>
                <tr class="<?= $class; ?>">
                    <td class="cell cell-id">
                        <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <?php echo $sample->getId(); ?>
                        </a>    
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $sample->getModel(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $sample->getCustomer(); ?>
                    </td>       
                    <td class="cell">
                        <a href="
                        <?php
                        echo $this->url(
                                'samples/list', ['search_by' => json_encode(['applicant' => $sample->getApplicant()->getId()])]);
                        ?>
                           ">                      
    <?php echo $sample->getApplicant()->getDisplayName(); ?>
                        </a>
                    </td>    
                    <td class="cell">
                        <a href="
                        <?php
                        echo $this->url(
                                'samples/list', ['search_by' => json_encode(['status' => $sample->getStatus()->getId()])]);
                        ?>                           
                           ">
    <?php echo $sample->getStatus()->getName(); ?>
                        </a>    
                    </td>  
                    <td class="cell text-center">
                        <?php
                        if (!empty($sample->getCurrentStatusDate())) {
                            echo $this->dateFormat(
                                $sample->getCurrentStatusDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        }
                        ?>                        
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>         
                    <td class="cell text-center">
                        <?php echo $sample->getQta(); ?>
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>      
                    <td class="cell text-center">
                        <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                            <?php
                            echo $this->dateFormat(
                                    $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                    IntlDateFormatter::NONE, // time
                                    "it_IT");
                            ?>       
                        <?php endif; ?>
                    </td>  
                    <td class="cell text-center">
    <?php echo count($sample->getAttachments()); ?>
                    </td>                      
                    <td class="cell cell-ctrls text-center">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                    </td>

                </tr>
<?php endforeach; ?>
        </tbody>
        </table>
    </div>



<?php
/*
  echo $this->paginationControl(
  $this->samples, 'Sliding', 'paginator-slide', array(
  'order_by' => $order_by,
  'order' => $order,
  'pageAction' => $pageAction,
  )
  );
 * 
 */


$this->headLink()
        ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css', 'all') //questo lo ricqarico xchè deve stare dopo
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-responsive/css/dataTables.responsive.css', 'all')
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css', 'all');
$this->headScript()->prependFile($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/plugins/datatables/media/js/jquery.dataTables.min.js');



$this->headScript()->appendScript("
$(function() {
    $('#example1').DataTable({
        order: [[ 0, \"desc\" ]],
        iDisplayLength: 100,
        bPaginate: false,
        responsive: false,
        aoColumnDefs: [
            { 'bSortable': false, 'aTargets': [ 5,6,8,9,11 ] }
        ] 
    });

}); 

");
