<?php echo $this->titleAndBread('Campionature'); ?>
<?php $this->myFlashMessenger(); ?>    

<!-- Lista campionature -->
<style>
 /* https://github.com/twbs/bootstrap/issues/9939 */
.btn-group {
  display: flex;
}
</style>
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                Trovate <strong><?php echo $totalRecord; ?></strong> campionature evase da inviare a magazzino.
            </div>
            <div class="col-md-6 right " style="text-align: right">     
                <a href="<?php echo $this->url('samples/processing') ?>" class="btn btn-primary" id="sendBtn">
                    <i class="fa fa-envelope"></i> Invia
                </a>                     
            </div>
        </div>
    </div>
</div>

<form id="sendForm" method="post">
    <div class="">
        <table class="table table-bordered table-hover" id="example1">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Modello</th>
                    <th>Cliente</th>    
                    <th>Richiedente</th>
                    <th>Stato</th>             
                    <th class="text-center">Qta</th>
                    <th class="text-center">Data consegna richiesta</th>
                    <th class="text-center">Data consegna prevista</th>
                    <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>
                    <th class="text-center"><i class="fa fa-paint-brush fa-fw"></i></th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->samples as $sample): ?>
                    <?php
                    $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());
                    ?>
                    <tr class="<?= $class; ?>">
                        <td class="cell text-center">
                            <input type="checkbox" name="selected[]" value="<?php echo $sample->getId(); ?>" />
                        </td>                    
                        <td class="cell cell-id">
                            <a href="<?php echo $this->url('samples/edit', array('sampleId' => $sample->getId())); ?>">                
                                <?php echo $sample->getId(); ?>                         
                            </a>    
                        </td>
                        <td class="cell cell-serial">
                            <?php echo $sample->getModel(); ?>
                        </td>         
                        <td class="cell">
                            <?php echo $sample->getCustomer(); ?>
                        </td>       
                        <td class="cell">
                            <?php echo $sample->getApplicant()->getDisplayName(); ?>
                        </td>    
                        <td class="cell">
                            <?php echo $sample->getStatus()->getName(); ?>
                        </td>     
                        <td class="cell text-center">
                            <?php echo $sample->getQta(); ?>
                        </td>                     
                        <td class="cell text-center">
                            <?php
                            echo $this->dateFormat(
                                    $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                    IntlDateFormatter::NONE, // time
                                    "it_IT");
                            ?>                        
                        </td>      
                        <td class="cell text-center">
                            <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                                <?php
                                echo $this->dateFormat(
                                        $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                        IntlDateFormatter::NONE, // time
                                        "it_IT");
                                ?>       
                            <?php endif; ?>
                        </td>  
                        <td class="cell text-center">
                            <?php echo count($sample->getAttachments()); ?>
                        </td>                      
                        <td class="cell text-center">
                            <?php if ($sample->getPainting()): ?>
                                <i class="fa fa-check fa-fw"></i>
                            <?php endif; ?>
                        </td>
                        <td class="cell cell-ctrls text-center">
                            <div class="btn-group">
                            <!--
                            <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                                <span class="glyphicon glyphicon-eye-open"></span> Show
                            </a>             
                            -->
                            <a class='btn btn-info btn-xs' href="<?php echo $this->url('samples/edit', array('sampleId' => $sample->getId())); ?>">
                                <span class="glyphicon glyphicon-edit"></span> Edit
                            </a><a href="<?php echo $this->url('samples/remove', array('sampleId' => $sample->getId())); ?>"
                               class="btn btn-danger btn-xs emodal-confirm">
                                <span class="glyphicon glyphicon-remove"></span> Del
                            </a>
                            </div>
                        </td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</form>

<?php
/*
  echo $this->paginationControl(
  $this->samples, 'Sliding', 'paginator-slide', array(
  'order_by' => $order_by,
  'order' => $order,
  'pageAction' => $pageAction,
  )
  );
 * 
 */


$this->headLink()
        ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css', 'all') //questo lo ricqarico xchè deve stare dopo
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-responsive/css/dataTables.responsive.css', 'all')
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css', 'all');
$this->headScript()->prependFile($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/plugins/datatables/media/js/jquery.dataTables.min.js');



$this->headScript()->appendScript("
$(function() {
    $('#sendBtn').click(function(event){
        $('#sendForm').trigger('submit');
        event.preventDefault();
    }); 

    $('#example1').DataTable({
        order: [[ 1, \"desc\" ]],
        iDisplayLength: 100,
        bPaginate: false,
        responsive: false,
        aoColumnDefs: [
            { 'bSortable': false, 'aTargets': [ 0,7,8,11 ] }
        ] 
    });

}); 

");
