<?php echo $this->titleAndBread('Spedizione'); ?>
<?php $this->myFlashMessenger(); ?> 

<!-- Form Comunicazione Campionatute pronte alla spedizione -->
<?php if (isset($showComunicateForm)): ?>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-envelope"></i> Comunicazione preparazione campionature
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <form role="form" method="post" action="<?= $this->url('samples/ship'); ?>">
                                <div class="form-group">
                                    <label>Peso</label>
                                    <input class="form-control" name="peso" placeholder="Esempio 1,2 Kg">
                                </div>
                                <div class="form-group">
                                    <label>Misure</label>
                                    <input class="form-control" name="misure" placeholder="Esempio 49 x 32 x 30,5 cm">
                                </div>
                                <div class="form-group">
                                    <label>Colli</label>
                                    <input type="number" name="colli" min="0" step="1" class="form-control" placeholder="Valore numerico">
                                </div>
                                <div class="form-group">
                                    <label>Note</label>
                                    <textarea class="form-control" rows="3" name="note"></textarea>
                                </div>
                                <input type="hidden" name="ids" value="<?= $ids; ?>" />
                                <button type="submit" class="btn btn-primary"><i class="fa fa-envelope"></i> Comunica</button>
                                <a class="btn btn-default" href="javascript: history.back()">Annulla</a>
                            </form>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                        <div class="col-lg-6">
                            <h3>Campionature selezionate</h3>
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Modello</th>
                                        <th>Cliente</th>    
                                        <th>Richiedente</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->samples as $sample): ?>
                                        <tr>
                                            <td class="cell cell-id">
                                                <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                                                    <?php echo $sample->getId(); ?>
                                                </a>    
                                            </td>
                                            <td class="cell cell-serial">
                                                <?php echo $sample->getModel(); ?>
                                            </td>         
                                            <td class="cell">
                                                <?php echo $sample->getCustomer(); ?>
                                            </td>       
                                            <td class="cell">
                                                <?php echo $sample->getApplicant()->getDisplayName(); ?>
                                            </td>    
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>


                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <?php return; ?>
<?php endif; ?>
<!-- Fine Form Comunicazione Campionatute pronte alla spedizione -->



<!-- Lista campionature -->
<div class="row">
    <div class="col-md-12">                

    </div>
</div>   
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                Trovate <strong><?php echo $totalRecord; ?></strong> campionature da gestire
            </div>
            <div class="col-md-6 right" style="text-align: right">
                <a href="<?php echo $this->url('samples/ship') ?>" class="btn btn-primary" id="shipMultiple">
                    <i class="fa fa-envelope"></i> Comunica multiplo
                </a>           
            </div>
        </div>
    </div>
</div>

<form id="shipForm" method="get">
    <div class="">
        <table class="table table-bordered table-hover" id="example1">
            <thead>
                <tr>
                    <th></th>
                    <th>Id</th>
                    <th>Modello</th>
                    <th>Cliente</th>    
                    <th>Richiedente</th>
                    <th class="text-center">Qta</th>
                    <th class="text-center">Data consegna richiesta</th>
                    <th class="text-center">Data consegna prevista</th>
                    <th class="text-center"><i class="fa fa-envelope fa-fw"></i></th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->samples as $sample): ?>
                    <?php
                    $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());
                    ?>
                    <tr class="<?= $class; ?>">
                        <td class="cell text-center">
                            <?php if (!$sample->getEmail1()): ?>
                                <input type="checkbox" name="selected[]" value="<?php echo $sample->getId(); ?>" />
                            <?php endif; ?>
                        </td>
                        <td class="cell cell-id">
                            <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                                <?php echo $sample->getId(); ?>
                            </a>    
                        </td>
                        <td class="cell cell-serial">
                            <?php echo $sample->getModel(); ?>
                        </td>         
                        <td class="cell">
                            <?php echo $sample->getCustomer(); ?>
                        </td>       
                        <td class="cell">
                            <?php echo $sample->getApplicant()->getDisplayName(); ?>
                        </td>      
                        <td class="cell text-center">
                            <?php echo $sample->getQta(); ?>
                        </td>                     
                        <td class="cell text-center">
                            <?php
                            echo $this->dateFormat(
                                    $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                    IntlDateFormatter::NONE, // time
                                    "it_IT");
                            ?>                        
                        </td>      
                        <td class="cell text-center">
                            <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                                <?php
                                echo $this->dateFormat(
                                        $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                        IntlDateFormatter::NONE, // time
                                        "it_IT");
                                ?>       
                            <?php endif; ?>
                        </td>                      
                        <td class="cell text-center">
                            <?php if ($sample->getEmail1()): ?>
                                <i class="fa fa-check fa-fw"></i>
                            <?php endif; ?>
                        </td>
                        <td class="cell cell-ctrls">
                            <div class="btn-group">
                            <?php if ($sample->getEmail1()): ?>
                                <a class='btn btn-success btn-xs ajax-ship' href="<?php echo $this->url('samples/history/shipping', array('sampleId' => $sample->getId())); ?>">
                                    <i class="fa fa-plane"></i> Spedisci
                                </a>     
                                <a class='btn btn-default btn-xs emodal-confirm' href="<?php echo $this->url('samples/ship', [], ['query' => ['sampleId' => $sample->getId(), 'up' => 1]]); ?>">
                                    <i class="fa fa-arrow-down"></i> Sposta sotto
                                </a>                               
                            <?php else: ?>
                                <a class='btn btn-primary btn-xs' href="<?php echo $this->url('samples/ship', [], ['query' => ['selected' => [$sample->getId()], 'comunicate' => 1]]); ?>">
                                    <i class="fa fa-envelope"></i> Comunica
                                </a>                         
                            <?php endif; ?>
                            </div>
                        </td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <input type="hidden" name="comunicate" value="1" />
</form>

<?php
//timeline
$this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/timeline.css', 'all');

//bootstrap table
$this->headLink()
        ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css', 'all') //questo lo ricqarico xchè deve stare dopo
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-responsive/css/dataTables.responsive.css', 'all')
        ->prependStylesheet($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css', 'all');
$this->headScript()->prependFile($this->basePath() . '/js/plugins/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/plugins/datatables/media/js/jquery.dataTables.min.js');

$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function() {

    $('#shipMultiple').click(function(event){
        $('#shipForm').trigger('submit');
        event.preventDefault();
    }); 


    $('.ajax-ship').click(function(e){
        var url = $(this).attr('href');
        ajaxRequest(url);
        e.preventDefault();
    });
    function ajaxRequest(url) {
        eModal.ajax({
            size: 'lg',
            url: url,
            buttons: [
                { text: 'Annnulla', close: true, style: 'default' }
            ]
        }, 'Spedisci campionatura');
    }

    $('#example1').DataTable({
        order: [[ 8,1, "desc" ]],
        iDisplayLength: 100,
        bPaginate: false,
        responsive: false,
        aoColumnDefs: [
            { 'bSortable': false, 'aTargets': [ 0,6,7,9 ] }
        ] 
    });


});
JS;
$this->inlineScript()->captureEnd();
?>
<!-- Fine Lista campionature -->




