<?php echo $this->titleAndBread('Campionature'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
$url_order = 'ASC';
if ($order_by == 'id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'customer') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'model') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}
?>
<div class="row">
    <div class="col-md-12">                
        Trovate <strong><?php echo $totalRecord; ?></strong> campionature aperte
    </div>
</div>   

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    <a href="<?php echo $this->url('samples/update', array_filter(array('order_by' => 'id', 'order' => $url_order))); ?>">
                        Id
                    </a> 
                    <?php if ($order_by == 'id'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/update', array_filter(array('order_by' => 'model', 'order' => $url_order))); ?>">
                        Modello
                    </a> 
                    <?php if ($order_by == 'model'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('samples/update', array_filter(array('order_by' => 'customer', 'order' => $url_order))); ?>">
                        Cliente
                    </a> 
                    <?php if ($order_by == 'customer'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>    
                <th>Richiedente</th>
                <th>Stato</th>             
                <th class="text-center">Qta</th>
                <th class="text-center">Data consegna richiesta</th>
                <th class="text-center">Data consegna prevista</th>
                <th class="text-center"><i class="fa fa-paperclip fa-fw"></i></th>
                <th class="text-center"><i class="fa fa-paint-brush fa-fw"></i></th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->samples as $sample): ?>
            <?php
            $class = \Samples\Entity\Status::getCssClass($sample->getStatus()->getId());   
            ?>
                <tr class="<?= $class; ?>">
                    <td class="cell cell-id">
                        <a href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <?php echo $sample->getId(); ?>
                        </a>    
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $sample->getModel(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $sample->getCustomer(); ?>
                    </td>       
                    <td class="cell">
                        <?php echo $sample->getApplicant()->getDisplayName(); ?>
                    </td>    
                    <td class="cell">
                        <?php echo $sample->getStatus()->getName(); ?>
                    </td>     
                    <td class="cell text-center">
                        <?php echo  $sample->getQta(); ?>
                    </td>                     
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $sample->getRequestedDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>      
                    <td class="cell text-center">
                        <?php if (!empty($sample->getScheduledDeliveryDate())): ?>
                        <?php
                        echo $this->dateFormat(
                                $sample->getScheduledDeliveryDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>       
                        <?php endif; ?>
                    </td>  
                    <td class="cell text-center">
                        <?php echo  count($sample->getAttachments()); ?>
                    </td>                      
                    <td class="cell text-center">
                        <?php if ($sample->getPainting()): ?>
                        <i class="fa fa-check fa-fw"></i>
                        <?php endif; ?>
                    </td>
                    <td class="cell cell-ctrls text-center">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('samples/show', array('sampleId' => $sample->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                        <a class='btn btn-info btn-xs' href="<?php echo $this->url('samples/edit', array('sampleId' => $sample->getId())); ?>">
                            <span class="glyphicon glyphicon-edit"></span> Edit
                        </a> 
                        <a href="<?php echo $this->url('samples/remove', array('sampleId' => $sample->getId())); ?>"
                            class="btn btn-danger btn-xs emodal-confirm">
                            <span class="glyphicon glyphicon-remove"></span> Del
                        </a>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->samples, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'pageAction' => $pageAction,
        )
);
?>
