Ciao,<br/>
sono state preparate le seguenti campionature che sono pronte per la spedizione:
<table style="margin-top: 20px; border: 1px solid #e9e9e9" cellpadding="5">
    <thead>
        <tr>
            <th>ID</th>
            <th>Modello</th>
            <th>Cliente</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($samples as $sample): ?>
        <tr>
            <td><?= $sample->getId(); ?></td>
            <td><?= $sample->getModel(); ?></td>
            <td><?= $sample->getCustomer(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<p>
<?php if (!empty($data['peso'])): ?>
<strong>Peso:</strong> <?= $data['peso'] . '<br/>'; ?>
<?php endif; ?>

<?php if (!empty($data['misure'])): ?>
<strong>Misure:</strong> <?= $data['misure'] . '<br/>'; ?>
<?php endif; ?>

<?php if (!empty($data['colli'])): ?>
<strong>Colli:</strong> <?= $data['colli'] . '<br/>'; ?>
<?php endif; ?>
</p>

<?php if (isset($data['note'])): ?>
<p><strong>Note:</strong><br/> <?= nl2br($data['note']); ?></p>
<?php endif; ?>

