<?php echo $this->titleAndBread('Cambia Password per ' . $this->zfcUserDisplayName()); ?>
<?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password modificata con successo.'); ?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-danger"><?php echo $this->translate('Impossibile modificare la password. Prova ancora.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);
?>

<div class = "row">
    <div class = "col-md-12">
<?= $this->ztbFormElement($form->get('identity')); ?>
    </div> 
</div>
<div class = "row">
    <div class = "col-md-12">
<?= $this->ztbFormElement($form->get('credential')); ?>
    </div> 
</div>
<div class = "row">
    <div class = "col-md-12">
<?= $this->ztbFormElement($form->get('newCredential')); ?>
    </div> 
</div>
<div class = "row">
    <div class = "col-md-12">
<?= $this->ztbFormElement($form->get('newCredentialVerify')); ?>
    </div> 
</div>
<div class = "row">
    <div class = "col-md-12">
<?= $this->ztbFormElement($form->get('submit')->setAttribute('class', 'btn btn-primary')->setValue('Cambia Password')); ?>
    </div> 
</div>


<?php echo $this->form()->closeTag(); ?>
