<?php
//setto qua il layout visto cne non sono riuscito ad eseguire l'override del controller
$this->layout('layout/login');
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');

$identity = $form->get('identity');
$identity->setAttributes(array(
    'class' => 'form-control',
    'type' => 'email',
    'placeholder' => $identity->getLabel(),
    'autofocus' => 'autofocus',
));

$credential = $form->get('credential');
$credential->setAttributes(array(
    'class' => 'form-control',
    'placeholder' => $credential->getLabel(),
));

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-lg btn-success btn-block');
$submit->setLabel('Login');
?>
<div style="text-align: center">
    <h1>
        <img src="<?php echo $this->basePath('img/logo-intranet.png') ?>" alt="Ariete Intranet"/>
    </h1>
    <h4 class="light-blue" id="id-company-text">© De'Longhi Appliances s.r.l - Divisione Commerciale Ariete</h4>
</div>
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
            <?php echo $this->form()->openTag($form) ?>
            <fieldset>                            
                <?php
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<div class="alert alert-danger">')
                        ->setMessageSeparatorString('</div><div class="help-inline">')
                        ->setMessageCloseString('</div>')
                        ->render($identity);
                ?>

                <div class="form-group">
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formInput($credential) ?>
                </div>
                <!--
                <div class="checkbox">
                    <label>
                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                    </label>
                </div>
                -->
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>                

                <!-- Change this to a button or input when using this as a form -->
                <?php echo $this->formButton($submit); ?>
            </fieldset>
            <?php echo $this->form()->closeTag() ?>
        </div>
        
        <?php if ($this->enableRegistration) : ?>
        <div class="panel-heading">
            <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
        </div>
        <?php endif; ?>
        
    </div>
</div>


<?php return; ?>
<h1>Login</h1>

<?php //$form = $this->zfcUserLoginWidget(array('render' => false));  ?>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

<dl class="zend_form">
    <?php echo $this->formElementErrors($form->get('identity')) ?>

    <dt><?php echo $this->formLabel($form->get('identity')) ?></dt>
    <dd><?php echo $this->formInput($form->get('identity')) ?></dd>

    <dt><?php echo $this->formLabel($form->get('credential')) ?></dt>
    <dd><?php echo $this->formInput($form->get('credential')) ?></dd>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>

    <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
</dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
    <?php echo $this->translate('Not registered?'); ?> <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a>
<?php endif; ?>