<?php echo $this->titleAndBread('Edit History'); ?>
<?php $this->myFlashMessenger(); ?>    

<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'edit-form');
$form->get('submit')->setValue('Edit History');
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class = "row">
        <div class = "col-md-6">
            <h3>Computer</h3>
        </div>    
        <div class = "col-md-6">
            <?= $this->ztbFormElement($form->get('recipient')); ?>
        </div>            
    </div>
    <div class = "row">
        <div class = "col-md-6">
            <?= $this->ztbFormElement($form->get('type')); ?>
        </div>    
        <div class = "col-md-6">
            <?= $this->ztbFormElement($form->get('status')); ?>
            <p class="help-block">Ha significato solo per tipo "Assegnazione"</p>
        </div>            
    </div>
    
<div>
    <?= $this->ztbFormElement($form->get('id')); ?>
    <?= $this->ztbFormElement($form->get('edit_by')); ?>
    <?= $this->ztbFormElement($form->get('computer')); ?>
    <?= $this->ztbFormElement($form->get('redirect')); ?>
    <?= $this->ztbFormElement($form->get('csrf')); ?>
    <?= $this->ztbFormElement($form->get('submit')); ?>
</div>    
<?php 
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {

}); 
");


