<?php echo $this->titleAndBread('Computers History'); ?>
<?php $this->myFlashMessenger(); ?>    


<div class="table">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Computer</th>
                <th>Azione</th>
                <th>Destinatario</th>
                <th>Stato</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->history as $row): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $row->getId(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $row->getComputer()->getSerial(); ?>
                    </td>  
                    <td class="cell cell-model">
                        <?php echo $row->getAttributes()['action']; ?>
                    </td>                    
                    <td class="cell cell-model">
                        <?php echo $row->getRecipient()->getDisplayName(); ?>
                    </td>                      
                    <td class="cell cell-model">
                        <?php echo $row->getStatus(); ?>
                    </td>                                      
                    <td class="cell cell-ctrls">
                        <a href="<?php echo $this->url('computer/history/edit', array('historyId' => $row->getId())); ?>">
                            <?php echo $this->translate('Edit') ?>
                        </a>
                        |
                        <a href="<?php echo $this->url('computer/history/remove', array('historyId' => $row->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete history?') ?>')">
                               <?php echo $this->translate('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->history, 'Sliding', 'paginator-slide', array(
    'order_by' => 'id',
    'order' => 'ASC',
    'search_by' => NULL,
    'pageAction' => $pageAction,
        )
);
?>


<?php
/* DataTables */
$this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/datatables/dataTables.bootstrap.css');

$this->headScript()
        ->appendFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.js')
        ->appendFile($this->basePath() . '/js/plugins/datatables/dataTables.bootstrap.js');

$this->inlineScript()->captureStart();
echo <<<JS
    $("#example1").dataTable();
JS;
$this->inlineScript()->captureEnd();
?>  