<?php echo $this->titleAndBread('Computers History'); ?>
<?php $this->myFlashMessenger(); ?>    


<div class="table">
    <table class="table table-bordered table-hover table-responsive" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Computer</th>
                <th>Azione</th>
                <th>Destinatario</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->history as $row): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $row->getId(); ?>
                    </td>
                    <td class="cell cell-model">
                        <a href="<?php echo $this->url('computer/show', array('computerId' => $row->getComputer()->getId())); ?>">
                            <?php echo $row->getComputer()->getSerial(); ?>
                        </a>                                               
                    </td>  
                    <td class="cell cell-model">
                        <?php echo $row->getAttributes()['action']; ?>
                    </td>                    
                    <td class="cell cell-model">
                        <a href="<?php echo $this->url('computer/userhistory', array('userId' => $row->getRecipient()->getId())); ?>">
                            <?php echo $row->getRecipient()->getDisplayName(); ?>
                        </a>                                               
                    </td>                                                          
                    <td class="cell cell-ctrls">
                        <a href="<?php echo $this->url('computer/history/edit', array('historyId' => $row->getId())); ?>">
                            <?php echo $this->translate('Edit') ?>
                        </a>
                        |
                        <a href="<?php echo $this->url('computer/history/remove', array('historyId' => $row->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete history?') ?>')">
                               <?php echo $this->translate('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->history, 'Sliding', 'paginator-slide', array(
    'order_by' => 'id',
    'order' => 'ASC',
    'search_by' => NULL,
    'pageAction' => $pageAction,
        )
);
?>
