<?php echo $this->doctype(); ?>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>    

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/custom.css', 'all')
                ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>       
    </head>

    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img style="width:200px" src="<?php echo $this->basePath('img/logo-intranet.png') ?>" alt="Ariete Intranet" style="vertical-align:baseline;"/>
                    </a>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <?php if ($this->zfcUserIdentity()): ?> 
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-user fa-fw"></i> <?= $this->zfcUserDisplayName(); ?>  <i class="fa fa-caret-down"></i> 
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <?php if ($this->zfcUserIdentity()->hasRole('admin')): ?>
                                    <li><a href="<?= $this->url('zfcadmin'); ?>"><i class="fa fa-lock fa-fw"></i> Admin</a></li>
                                <?php endif; ?>                            
                                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                                </li>
                                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                                </li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="fa fa-sign-out fa-fw"></i> <?php echo $this->translate('Sign Out'); ?></a>
                                </li>
                            </ul>
                            <!-- /.dropdown-user -->
                        </li>
                        <!-- /.dropdown -->
                    <?php endif; ?>

                    <li id="sidebar-toggle">
                        <a href="#">
                            <i class="fa fa-bars fa-fw"></i>  
                        </a>
                    </li>     

                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation" id="sidebar">
                    <div class="sidebar-nav navbar-collapse">

                        <?php
                        echo $this->navigation('left_navigation')
                                ->menu()
                                ->setUlClass('nav')
                                ->setMaxDepth(1)
                                ->setPartial(array('partial/leftnav.phtml', 'Application'))
                                ->setRenderInvisible(true)
                        ?>                
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <!-- Page Content -->
            <div id="page-wrapper">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12">
                            <?php echo $this->content; ?>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- /#page-wrapper -->        


        </div>    
        <!-- /#wrapper -->   

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/sb-admin-2.js')
                ->prependFile($this->basePath() . '/js/plugins/metisMenu/jquery.metisMenu.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
        ;
        ?>   

        <?php echo $this->inlineScript() ?>

    </body>

</html>