<?php echo $this->doctype(); ?>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <?php echo $this->headTitle('Ariete Intranet')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>    

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/custom.css', 'all')
                ->prependStylesheet($this->basePath() . '/css/sb-admin-2.css')
                ->prependStylesheet($this->basePath() . '/font-awesome-4.2.0/css/font-awesome.css')
                ->prependStylesheet($this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>                              
    </head>

    <body class="blur-login">

        <div class="container">
            <div class="row">
                <?php echo $this->content; ?>
            </div>
        </div>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/sb-admin-2.js')
                ->prependFile($this->basePath() . '/js/plugins/metisMenu/jquery.metisMenu.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.10.2.js');
        ?>  

        <?php echo $this->inlineScript() ?>

    </body>

</html>

