<?php
/**
  echo $this->headLink()
  ->appendStylesheet($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css');
  echo $this->headScript()
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.min.js')
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput-angular.js');
 * 
 */
$title = 'Add Computer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'create-form');
$form->get('submit')->setValue('Add new computer');
$sample = $form->get('computer'); //fieldset
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class = "row">
        <div class = "col-md-6">
<fieldset>
    <legend>Anagrafica</legend>            
            <?= $this->ztbFormElement($sample->get('serial')); ?>
            <?= $this->ztbFormElement($sample->get('model')); ?>
            <?= $this->ztbFormElement($sample->get('status')); ?>
</fieldset>
        </div>
        <div class = "col-md-6">
<fieldset>
    <legend>Caratteristiche</legend>            
            <?= $this->ztbFormElement($sample->get('category')); ?>
            <?= $this->ztbFormElement($sample->get('brand')); ?>
            <?= $this->ztbFormElement($sample->get('processor')); ?>
</fieldset>    
        </div>       
    </div>
<fieldset>
    <legend>Fatturazione</legend>
     <div class = "row">
        <div class = "col-md-6">
            <?= $this->ztbFormElement($sample->get('ddt')); ?>
        </div>     
        <div class = "col-md-6">
            <?= $this->ztbFormElement($sample->get('ddtDate')); ?>
        </div>           
    </div>      
     <div class = "row">         
        <div class = "col-md-6">
            <?= $this->ztbFormElement($sample->get('invoice')); ?>
        </div>     
        <div class = "col-md-6">
            <?= $this->ztbFormElement($sample->get('invoiceDate')); ?>
        </div>           
    </div>     
</fieldset>

     
    
<div>
    <?= $this->ztbFormElement($form->get('csrf')); ?>
    <?= $this->ztbFormElement($form->get('submit')); ?>
</div>    
<?php 
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {
    //Setto stato di default 'Attivo'
    $('#status').val('1');
}); 

");


