<?php echo $this->titleAndBread('Add Computer'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
/**
  echo $this->headLink()
  ->appendStylesheet($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css');
  echo $this->headScript()
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.min.js')
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput-angular.js');
 * 
 */
?>
<?php
$this->headLink()
        ->appendStylesheet('http://silviomoreto.github.io/bootstrap-select/bootstrap-select.min.css');
$this->headScript()
        ->prependFile('http://silviomoreto.github.io/bootstrap-select/bootstrap-select.min.js');
?>

<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'create-form');
$form->get('submit')->setValue('Add new computer');
$fieldset = $form->get('computer'); //fieldset
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class = "row">
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Anagrafica
            </div>
            <div class="panel-body">
                <?php echo $this->ztbFormElement($fieldset->get('serial')); ?>
                <?php echo $this->ztbFormElement($fieldset->get('model')); ?>
                <?php echo $this->ztbFormElement($fieldset->get('status')); ?>
            </div>    
        </div>
    </div>
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Caratteristiche
            </div>
            <div class="panel-body">           
                <?php echo $this->ztbFormElement($fieldset->get('category')); ?>
                <?php echo $this->ztbFormElement($fieldset->get('brand')); ?>
                <?php echo $this->ztbFormElement($fieldset->get('processor')); ?>
            </div>   
        </div>
    </div>       
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        Fatturazione
    </div>
    <div class="panel-body">
        <div class = "row">
            <div class = "col-md-6">
                <?php echo $this->ztbFormElement($fieldset->get('ddt')); ?>
            </div>     
            <div class = "col-md-6">
                <?php echo $this->ztbFormElement($fieldset->get('ddtDate')); ?>
            </div>           
        </div>      
        <div class = "row">         
            <div class = "col-md-6">
                <?php echo $this->ztbFormElement($fieldset->get('invoice')); ?>
            </div>     
            <div class = "col-md-6">
                <?php echo $this->ztbFormElement($fieldset->get('invoiceDate')); ?>
            </div>           
        </div> 
    </div>
</div>
<div class = "row">         
    <div class = "col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <i class="fa fa-user"></i> Utente
            </div>
            <div class="panel-body">        
        <?php echo $this->ztbFormElement($fieldset->get('recipient')); ?>
                </div></div>
    </div>               
</div>

<div>
    <?= $this->ztbFormElement($form->get('csrf')); ?>
    <?= $this->ztbFormElement($form->get('submit')); ?>
</div>    
<?php 
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {
    //Setto stato di default 'Attivo'
    $('#status').val('1');
}); 

");


