<?php echo $this->titleAndBread('Computers'); ?>
<?php $this->myFlashMessenger(); ?>   

<div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-laptop fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><?= $computerCount; ?></div>
                                    <div>Computers presenti!</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->url('computer/list'); ?>">
                            <div class="panel-footer">
                                <span class="pull-left">Mostra</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-gears fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">3</div>
                                    <div>Settings</div>
                                </div>
                            </div>
                        </div>
                        <a href="<?php echo $this->url('computer/settings'); ?>">
                            <div class="panel-footer">
                                <span class="pull-left">Mostra</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-yellow">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-area-chart fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge">2</div>
                                    <div>Statistiche</div>
                                </div>
                            </div>
                        </div>
                        <a href="#">
                            <div class="panel-footer">
                                <span class="pull-left">Mostra</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>

            </div>














            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Ultimi inserimenti
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Seriale</th>
                <th>Modello</th>    
                <th>Destinatario</th>
                <th>Stato</th>
                <th>Categoria</th>
                <th>Brand</th>
                <th>Possessore</th>
                <th>Action</th>
            </tr>
        </thead>    
            <?php foreach ($this->computers as $computer): ?>
<?php
                                switch ($computer->getStatus()->getId()) {
                                    case 1:
                                        $statusClass = 'success';
                                        break;
                                    case 2:
                                        $statusClass = 'warning';
                                        break;
                                    case 3:
                                        $statusClass = 'danger';
                                        break;                                    
                                    default:
                                        break;
                                }
?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $computer->getId(); ?>
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $computer->getSerial(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $computer->getModel(); ?>
                    </td>     
                    <td class="cell">
                        <a href="<?php echo $this->url('computer/userhistory', array('userId' => $computer->getRecipient()->getId())); ?>">
                            <?php echo $computer->getRecipient()->getDisplayName(); ?>
                        </a>                          
                    </td>  
                    <td class="cell text-center">
                        <span class="label label-<?php echo $statusClass; ?>">
                            <?php echo $computer->getStatus()->getName(); ?>
                        </span>
                    </td>                       
                    <td class="cell">
                        <?php echo $computer->getCategory()->getName(); ?>
                    </td>   
                    <td class="cell">
                        <?php echo $computer->getBrand()->getName(); ?>
                    </td>   
                    <td class="cell">
                        <?php echo $computer->getProcessor()->getName(); ?>
                    </td>                                       
                    <td class="cell cell-ctrls text-center">
                        <div class=" btn-group">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('computer/show', array('computerId' => $computer->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                        <a class='btn btn-info btn-xs' href="<?php echo $this->url('computer/edit', array('computerId' => $computer->getId())); ?>">
                            <span class="glyphicon glyphicon-edit"></span> Edit
                        </a> 
                        <a href="<?php echo $this->url('computer/remove', array('computerId' => $computer->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete computer?') ?>')" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-remove"></span> Del
                        </a>
                        </div>
                    </td>

                </tr>
            <?php endforeach; ?>        
        
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Per Brand
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-brand"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->
                <div class="col-lg-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Per categoria
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="flot-chart">
                                <div class="flot-chart-content" id="flot-pie-category"></div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-6 -->


            </div>

<!-- Flot Charts JavaScript --> 
<?php
$this->headScript()
        //->prependFile($this->basePath() . '/js/plugins/flot/flot-data.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.tooltip.min.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.resize.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.pie.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/jquery.flot.js')
        ->prependFile($this->basePath() . '/js/plugins/flot/excanvas.min.js');


$pieBrandData = '';
foreach ($chartPieBrand as $item) {
    $pieBrandData .= '{label: "' . $item['name'] . '",data: ' . $item['nr']. '}, ' . PHP_EOL;
}

$pieCategoryData = '';
foreach ($chartPieCategory as $item) {
    $pieCategoryData .= '{label: "' . $item['name'] . '",data: ' . $item['nr']. '}, ' . PHP_EOL;
}

$this->headScript()->appendScript("
$(function() {
//Flot Pie Chart
$(function() {

    //Brand
    var dataBrand = [" . $pieBrandData . "];
    var plotObj = $.plot($(\"#flot-pie-brand\"), dataBrand, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: \"%p.0%, %s\", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });
    
    //Category
    var dataCategory = [" . $pieCategoryData . "];
    var plotObj = $.plot($(\"#flot-pie-category\"), dataCategory, {
        series: {
            pie: {
                show: true
            }
        },
        grid: {
            hoverable: true
        },
        tooltip: true,
        tooltipOpts: {
            content: \"%p.0%, %s\", // show percentages, rounding to 2 decimal places
            shifts: {
                x: 20,
                y: 0
            },
            defaultTheme: false
        }
    });

});


}); 

");