<?php echo $this->titleAndBread('Computers List'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
$url_order = 'ASC';
if ($order_by == 'id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'serial') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'model') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}
?>
<div class="row">
    <div class="col-md-12">                
        Trovati <?php echo $totalRecord; ?> computers
    </div>
</div>   
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                <a href="<?php echo $this->url('computer/create') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Aggiungi nuovo computer') ?>
                </a>
            </div>
            <div class="col-md-6">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('computer/search'));
                $form->setAttribute('class', 'navbar-form navbar-right');
                $form->prepare();

                echo $this->form()->openTag($form);
                foreach ($form as $element) :
                    ?>
                    <div class="form-group <?php if ($this->formElementErrors($element)) echo "error" ?>">

                        <?php
                        echo $this->formElement($element);
                        if ($this->formElementErrors($element)):
                            ?>
                            <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
                            <?php
                        endif;
                        ?>

                    </div>
                    <?php
                endforeach;
                echo $this->form()->closeTag();
                ?>               
            </div>
        </div>
    </div>
</div>

<div class="table">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'id', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Id
                    </a> 
                    <?php if ($order_by == 'id'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'serial', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Seriale
                    </a> 
                    <?php if ($order_by == 'serial'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'model', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Modello
                    </a> 
                    <?php if ($order_by == 'model'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>    
                <th>
                    Possessore
                </th>
                <th>Stato</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->computers as $computer): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $computer->getId(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $computer->getSerial(); ?>
                    </td>         
                    <td class="cell cell-model">
                        <?php echo $computer->getModel(); ?>
                    </td>     
                    <td class="cell cell-model">
                        <?php echo $computer->getRecipient()->getDisplayName(); ?>
                    </td>                        
                    <td class="cell cell-model">
                        <?php if (null !== $computer->getStatus()): ?>
                            <?php echo $computer->getStatus()->getName(); ?>
                        <?php endif; ?>
                    </td>                   
                    <td class="cell cell-ctrls">
                        <a href="<?php echo $this->url('computer/show', array('computerId' => $computer->getId())); ?>">
                            <?php echo $this->translate('Show') ?>
                        </a>
                        |                        
                        <a href="<?php echo $this->url('computer/edit', array('computerId' => $computer->getId())); ?>">
                            <?php echo $this->translate('Edit') ?>
                        </a>
                        |
                        <a href="<?php echo $this->url('computer/remove', array('computerId' => $computer->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete computer?') ?>')">
                               <?php echo $this->translate('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->computers, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);
?>
