<?php echo $this->titleAndBread('Computers List'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
$url_order = 'ASC';
if ($order_by == 'id') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'serial') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
} elseif ($order_by == 'model') {
    $url_order = ($order == 'ASC' ) ? 'DESC' : 'ASC';
}
?>
<div class="row">
    <div class="col-md-12">                
        Trovati <?php echo $totalRecord; ?> computers
    </div>
</div>   
<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                <a href="<?php echo $this->url('computer/create') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Aggiungi nuovo computer') ?>
                </a>
            </div>
            <div class="col-md-6">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('computer/search'));
                $form->setAttribute('class', 'navbar-form navbar-right');
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formSearch($form->get('search'));
                echo $this->formButton()->render($form->get('submit'), 'Go!');

                echo $this->form()->closeTag();
                ?>               
            </div>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'id', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Id
                    </a> 
                    <?php if ($order_by == 'id'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'serial', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Seriale
                    </a> 
                    <?php if ($order_by == 'serial'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>
                <th>
                    <a href="<?php echo $this->url('computer/list', array_filter(array('order_by' => 'model', 'order' => $url_order, 'search_by' => $search_by))); ?>">
                        Modello
                    </a> 
                    <?php if ($order_by == 'model'): ?><i class="fa fa-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?>
                </th>    
                <th>Destinatario</th>
                <th>Stato</th>
                <th>Categoria</th>
                <th>Brand</th>
                <th>Possessore</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->computers as $computer): ?>
<?php
                                switch ($computer->getStatus()->getId()) {
                                    case 1:
                                        $statusClass = 'success';
                                        break;
                                    case 2:
                                        $statusClass = 'warning';
                                        break;
                                    case 3:
                                        $statusClass = 'danger';
                                        break;                                    
                                    default:
                                        break;
                                }
?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $computer->getId(); ?>
                    </td>
                    <td class="cell cell-serial">
                        <?php echo $computer->getSerial(); ?>
                    </td>         
                    <td class="cell">
                        <?php echo $computer->getModel(); ?>
                    </td>     
                    <td class="cell">
                        <a href="<?php echo $this->url('computer/userhistory', array('userId' => $computer->getRecipient()->getId())); ?>">
                            <?php echo $computer->getRecipient()->getDisplayName(); ?>
                        </a>                          
                    </td>  
                    <td class="cell text-center">
                        <span class="label label-<?php echo $statusClass; ?>">
                            <?php echo $computer->getStatus()->getName(); ?>
                        </span>
                    </td>                       
                    <td class="cell">
                        <?php echo $computer->getCategory()->getName(); ?>
                    </td>   
                    <td class="cell">
                        <?php echo $computer->getBrand()->getName(); ?>
                    </td>   
                    <td class="cell">
                        <?php echo $computer->getProcessor()->getName(); ?>
                    </td>                                       
                    <td class="cell cell-ctrls text-center">
                        <a class='btn btn-default btn-xs' href="<?php echo $this->url('computer/show', array('computerId' => $computer->getId())); ?>">
                            <span class="glyphicon glyphicon-eye-open"></span> Show
                        </a>                         
                        <a class='btn btn-info btn-xs' href="<?php echo $this->url('computer/edit', array('computerId' => $computer->getId())); ?>">
                            <span class="glyphicon glyphicon-edit"></span> Edit
                        </a> 
                        <a href="<?php echo $this->url('computer/remove', array('computerId' => $computer->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete computer?') ?>')" class="btn btn-danger btn-xs">
                            <span class="glyphicon glyphicon-remove"></span> Del
                        </a>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->computers, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);
?>
