<?php echo $this->titleAndBread('Computers List'); ?>
<?php $this->myFlashMessenger(); ?>    

<div class="panel panel-default">
    <div class="panel-body">
        <a href="<?php echo $this->url('computer/create') ?>" class="btn btn-primary">
            <?php echo $this->translate('Aggiungi nuovo computer') ?>
        </a>
    </div>
</div>

<div class="table">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Modello</th>
                <th>Seriale</th>
                <th>Stato</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->computers as $computer): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $computer->getId(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $computer->getModel(); ?>
                    </td>
                    <td class="cell cell-model">
                        <?php echo $computer->getSerial(); ?>
                    </td>                    
                    <td class="cell cell-model">
                        <?php if (null !== $computer->getStatus()): ?>
                        <?php echo $computer->getStatus()->getName(); ?>
                        <?php endif; ?>
                    </td>                   
                    <td class="cell cell-ctrls">
                        <a href="<?php echo $this->url('computer/edit', array('computerId' => $computer->getId())); ?>">
                            <?php echo $this->translate('Edit') ?>
                        </a>
                        |
                        <a href="<?php echo $this->url('computer/remove', array('computerId' => $computer->getId())); ?>"
                           onclick="return confirm('<?php echo $this->translate('Really delete computer?') ?>')">
                               <?php echo $this->translate('Delete') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->computers, 'Sliding', 'paginator-slide', array(
    'order_by' => 'id',
    'order' => 'ASC',
    'search_by' => NULL,
    'pageAction' => $pageAction,
        )
);
?>


<?php
/* DataTables */
$this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/datatables/dataTables.bootstrap.css');

$this->headScript()
        ->appendFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.js')
        ->appendFile($this->basePath() . '/js/plugins/datatables/dataTables.bootstrap.js');

$this->inlineScript()->captureStart();
echo <<<JS
                $("#example1").dataTable();
                $('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": false,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });
JS;
$this->inlineScript()->captureEnd();
?>  