<h1><?php echo $this->translate('Settings') ?></h1>

<?php
// In any of your .phtml files:
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>








<div class="row">
    <!-- Categories -->
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Categorie
                <div class="pull-right">
                    <a href="<?php echo $this->url('computer/category/create') ?>" class="btn btn-primary btn-xs">
                        <span class="fa fa-file-o"></span>
                        <?php echo $this->translate('Aggiungi nuova') ?>
                    </a>                     
                 </div>                
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table">
                    <table class="table table-bordered table-hover" id="category-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Stato</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->categories as $category): ?>
                                <tr>
                                    <td class="cell cell-id">
                                        <?php echo $category->getId(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $category->getName(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $category->getStatus(); ?>
                                    </td>                                      
                                    <td class="cell cell-ctrls">
                                        <a href="<?php echo $this->url('computer/category/edit', array('categoryId' => $category->getId())); ?>">
                                            <?php echo $this->translate('Edit') ?>
                                        </a>
                                        |
                                        <a href="<?php echo $this->url('computer/category/remove', array('categoryId' => $category->getId())); ?>"
                                           onclick="return confirm('<?php echo $this->translate('Really delete category?') ?>')">
                                               <?php echo $this->translate('Delete') ?>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /categories -->
    
    <!-- Brands -->
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Brands
                <div class="pull-right">
                    <a href="<?php echo $this->url('computer/brand/create') ?>" class="btn btn-primary btn-xs">
                        <span class="fa fa-file-o"></span>
                        <?php echo $this->translate('Aggiungi nuovo') ?>
                    </a>                     
                 </div>                
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table">
                    <table class="table table-bordered table-hover" id="brand-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Stato</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->brands as $brand): ?>
                                <tr>
                                    <td class="cell cell-id">
                                        <?php echo $brand->getId(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $brand->getName(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $brand->getStatus(); ?>
                                    </td>                                      
                                    <td class="cell cell-ctrls">
                                        <a title="Edit" class="btn btn-default btn-circle"  href="<?php echo $this->url('computer/brand/edit', array('brandId' => $brand->getId())); ?>">
                                            <i class="fa fa-edit"></i>
                                        </a>

                                        <a title="Eelete" class="btn btn-danger btn-circle" href="<?php echo $this->url('computer/brand/remove', array('brandId' => $brand->getId())); ?>"
                                           onclick="return confirm('<?php echo $this->translate('Really delete brand?') ?>')">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /brands -->
    
    <!-- Processor -->
    <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Processori
                <div class="pull-right">
                    <a href="<?php echo $this->url('computer/processor/create') ?>" class="btn btn-primary btn-xs">
                        <span class="fa fa-file-o"></span>
                        <?php echo $this->translate('Aggiungi nuovo') ?>
                    </a>                     
                 </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body"> 
                <div class="table">
                    <table class="table table-bordered table-hover" id="processor-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nome</th>
                                <th>Stato</th>
                                <th>&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->processors as $processor): ?>
                                <tr>
                                    <td class="cell cell-id">
                                        <?php echo $processor->getId(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $processor->getName(); ?>
                                    </td>
                                    <td class="cell cell-model">
                                        <?php echo $processor->getStatus(); ?>
                                    </td>                                      
                                    <td class="cell cell-ctrls">
                                        <a title="Edit" class="btn btn-default btn-circle"  href="<?php echo $this->url('computer/processor/edit', array('processorId' => $processor->getId())); ?>">
                                            <i class="fa fa-edit"></i>
                                        </a>

                                        <a title="Eelete" class="btn btn-danger btn-circle" href="<?php echo $this->url('computer/processor/remove', array('processorId' => $processor->getId())); ?>"
                                           onclick="return confirm('<?php echo $this->translate('Really delete processor?') ?>')">
                                            <i class="fa fa-trash-o"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->               
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /processor -->    
</div>

<?php
/* DataTables */
$this->headLink()->appendStylesheet($this->basePath() . '/css/plugins/dataTables.bootstrap.css');

$this->headScript()
        ->appendFile($this->basePath() . '/js/plugins/datatables/jquery.dataTables.js')
        ->appendFile($this->basePath() . '/js/plugins/datatables/dataTables.bootstrap.js');

$this->inlineScript()->captureStart();
echo <<<JS
    $("#category-table").dataTable();
    $("#brand-table").dataTable();
    $("#processor-table").dataTable();
JS;
$this->inlineScript()->captureEnd();
?>  