<?php echo $this->titleAndBread('Show Computer') ?>
<?php $this->myFlashMessenger(); ?>   
<?php
$status = $computer->getStatus()->getId();
switch ($status) {
    case 2:
        $class = 'yellow';
        $icon = 'database';
        break;
    case 3:
        $class = 'red';
        $icon = 'trash';
        break;
    default:
        $class = 'green';
        $icon = 'check';
        break;
}
?>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-<?php echo $class; ?>">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-<?php echo $icon; ?> fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo $computer->getStatus()->getName(); ?></div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <div class="col-md-6">
        <h3>Inserito il:
            <small><?php
                echo $this->dateFormat(
                        $computer->getCreatedDate(), IntlDateFormatter::LONG, // date
                        IntlDateFormatter::SHORT, // time
                        "it_IT");
                ?></small>
        </h3>       
        <h3>Ultima modifica:
            <small><?php
                echo $this->dateFormat(
                        $computer->getEditDate(), IntlDateFormatter::LONG, // date
                        IntlDateFormatter::SHORT, // time
                        "it_IT");
                ?></small>
        </h3>           
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $computer->getSerial(); ?>
            </div>
            <div class="panel-body">
                <h2>Seriale:
                    <small><?php echo $computer->getSerial(); ?></small>
                </h2>
                <h2>Modello:
                    <small><?php echo $computer->getModel(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>Categoria:
                    <small><?php echo $computer->getCategory()->getName(); ?></small>
                </h2>
                <h2>Brand:
                    <small><?php echo $computer->getBrand()->getName(); ?></small>
                </h2>
                <h2>Processore:
                    <small><?php echo $computer->getProcessor()->getName(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>DDT:
                    <small><?php echo $computer->getDdt(); ?></small>
                </h2>        
                <h2>Data DDT:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getDdtDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?></small>
                </h2>    
                <h2>Fattura:
                    <small><?php echo $computer->getInvoice(); ?></small>
                </h2>        
                <h2>Data Fattura:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getInvoiceDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?></small>
                </h2>                 
            </div>
            <!-- /.panel-body -->
        </div>        
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i> History
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="timeline">
                    <?php
                    $count = 0;
                    $history = $computer->getHistory();
                    foreach ($history as $row):
                        $count++;
                        $timelineClass = (($count % 2) == 0) ? 'timeline-inverted' : '';
                        $desc = $row->getAttributes()['description'];
                        if ($row->getType() == 3) {
                            
                        }
                        ?>
                        <li class="<?php echo $timelineClass; ?>">
                            <div class="timeline-badge <?php echo $row->getAttributes()['class']; ?>"><i class="fa <?php echo $row->getAttributes()['icon']; ?>"></i>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="timeline-title"><?php echo $row->getAttributes()['action']; ?></h4>
                                    <p><small class="text-muted"><i class="fa fa-clock-o"></i> <?php
                                            echo $this->dateFormat(
                                                    $row->getEditDate(), IntlDateFormatter::LONG, // date
                                                    IntlDateFormatter::SHORT, // time
                                                    "it_IT");
                                            ?></small>
                                    </p>
                                </div>
                                <div class="timeline-body">
                                    <p><?php echo $row->getAttributes()['description']; ?></p>
                                    <hr>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-gear"></i>  <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="<?php echo $this->url('computer/history/edit', array('historyId' => $row->getId())); ?>">
                                                    <?php echo $this->translate('Edit') ?>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url('computer/history/remove', array('historyId' => $row->getId())); ?>"
                                                   onclick="return confirm('<?php echo $this->translate('Really delete history?') ?>')">
                                                       <?php echo $this->translate('Delete') ?>
                                                </a>                                            
                                            </li>
                                        </ul>
                                    </div>                                
                                </div>
                            </div>
                        </li>                    
                    <?php endforeach; ?>                    

                    <li>
                        <div class="timeline-badge"><i class="fa fa-check"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                                <p><small class="text-muted"><i class="fa fa-clock-o"></i> 11 hours ago via Twitter</small>
                                </p>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero laboriosam dolor perspiciatis omnis exercitationem. Beatae, officia pariatur? Est cum veniam excepturi. Maiores praesentium, porro voluptas suscipit facere rem dicta, debitis.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-badge warning"><i class="fa fa-credit-card"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem dolorem quibusdam, tenetur commodi provident cumque magni voluptatem libero, quis rerum. Fugiat esse debitis optio, tempore. Animi officiis alias, officia repellendus.</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium maiores odit qui est tempora eos, nostrum provident explicabo dignissimos debitis vel! Adipisci eius voluptates, ad aut recusandae minus eaque facere.</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-badge danger"><i class="fa fa-bomb"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus numquam facilis enim eaque, tenetur nam id qui vel velit similique nihil iure molestias aliquam, voluptatem totam quaerat, magni commodi quisquam.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates est quaerat asperiores sapiente, eligendi, nihil. Itaque quos, alias sapiente rerum quas odit! Aperiam officiis quidem delectus libero, omnis ut debitis!</p>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-badge info"><i class="fa fa-save"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis minus modi quam ipsum alias at est molestiae excepturi delectus nesciunt, quibusdam debitis amet, beatae consequuntur impedit nulla qui! Laborum, atque.</p>
                                <hr>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-gear"></i>  <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Action</a>
                                        </li>
                                        <li><a href="#">Another action</a>
                                        </li>
                                        <li><a href="#">Something else here</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi fuga odio quibusdam. Iure expedita, incidunt unde quis nam! Quod, quisquam. Officia quam qui adipisci quas consequuntur nostrum sequi. Consequuntur, commodi.</p>
                            </div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-badge success"><i class="fa fa-graduation-cap"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4 class="timeline-title">Lorem ipsum dolor</h4>
                            </div>
                            <div class="timeline-body">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deserunt obcaecati, quaerat tempore officia voluptas debitis consectetur culpa amet, accusamus dolorum fugiat, animi dicta aperiam, enim incidunt quisquam maxime neque eaque.</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- /.panel-body -->
        </div>  
    </div>        
</div>    

<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/timeline.css');

$history = $computer->getHistory();
foreach ($history as $row) {
    var_dump($row->getRecipient()->getDisplayName());
}