<?php echo $this->titleAndBread('Show Computer') ?>
<?php $this->myFlashMessenger(); ?>    
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <?php echo $computer->getSerial(); ?>
            </div>
            <div class="panel-body">
                <h2>Seriale:
                    <small><?php echo $computer->getSerial(); ?></small>
                </h2>
                <h2>Modello:
                    <small><?php echo $computer->getModel(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>Categoria:
                    <small><?php echo $computer->getCategory()->getName(); ?></small>
                </h2>
                <h2>Brand:
                    <small><?php echo $computer->getBrand()->getName(); ?></small>
                </h2>
                <h2>Processore:
                    <small><?php echo $computer->getProcessor()->getName(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>DDT:
                    <small><?php echo $computer->getDdt(); ?></small>
                </h2>        
                <h2>Data DDT:
                    <small><?php echo $this->dateFormat(
                            $computer->getDdtDate(),
                            IntlDateFormatter::LONG, // date
                            IntlDateFormatter::NONE, // time
                            "it_IT"); ?></small>
                </h2>    
                <h2>Fattura:
                    <small><?php echo $computer->getInvoice(); ?></small>
                </h2>        
                <h2>Data Fattura:
                    <small><?php echo $this->dateFormat(
                            $computer->getInvoiceDate(),
                            IntlDateFormatter::LONG, // date
                            IntlDateFormatter::NONE, // time
                            "it_IT"); ?></small>
                </h2>                 
            </div>
            <!-- /.panel-body -->
        </div>        
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Storico
            </div>
            <div class="panel-body">
                <h1>Heading 1
                    <small>Sub-heading</small>
                </h1>
                <h2>Heading 2
                    <small>Sub-heading</small>
                </h2>
                <h3>Heading 3
                    <small>Sub-heading</small>
                </h3>
                <h4>Heading 4
                    <small>Sub-heading</small>
                </h4>
                <h5>Heading 5
                    <small>Sub-heading</small>
                </h5>
                <h6>Heading 6
                    <small>Sub-heading</small>
                </h6>
            </div>
            <!-- /.panel-body -->
        </div>        
    </div>        
</div>    
</div>
<?php
$this->headScript()->appendScript("
$(function() {

}); 

");
