<?php echo $this->titleAndBread('Show Computer') ?>
<?php $this->myFlashMessenger(); ?>   
<?php
$status = $computer->getStatus()->getId();
switch ($status) {
    case 2:
        $class = 'yellow';
        $icon = 'database';
        break;
    case 3:
        $class = 'red';
        $icon = 'trash';
        break;
    default:
        $class = 'green';
        $icon = 'check';
        break;
}
?>
<div class="row">
    <div class="col-md-12">

    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-<?php echo $class; ?>">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-<?php echo $icon; ?> fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo $computer->getStatus()->getName(); ?></div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
    <div class="col-md-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo $computer->getRecipient()->getDisplayName(); ?></div>
                    </div>
                </div>
            </div>
        </div>           
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-laptop fa-fw"></i>
                <?php echo $computer->getSerial(); ?>

                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li>
                                <a href="<?php echo $this->url('computer/edit', array('computerId' => $computer->getId())); ?>">
                                    <?php echo $this->translate('Edit') ?>
                                </a>                                
                            </li>
                            <li>
                                <a href="<?php echo $this->url('computer/remove', array('computerId' => $computer->getId())); ?>"
                                   onclick="return confirm('<?php echo $this->translate('Really delete computer?') ?>')">
                                       <?php echo $this->translate('Delete') ?>
                                </a>                                
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <h2>Seriale:
                    <small><?php echo $computer->getSerial(); ?></small>
                </h2>
                <h2>Modello:
                    <small><?php echo $computer->getModel(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>Categoria:
                    <small><?php echo $computer->getCategory()->getName(); ?></small>
                </h2>
                <h2>Brand:
                    <small><?php echo $computer->getBrand()->getName(); ?></small>
                </h2>
                <h2>Processore:
                    <small><?php echo $computer->getProcessor()->getName(); ?></small>
                </h2>
                <hr class="devider devider-db-dotted">
                <h2>DDT:
                    <small><?php echo $computer->getDdt(); ?></small>
                </h2>        
                <h2>Data DDT:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getDdtDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?></small>
                </h2>    
                <h2>Fattura:
                    <small><?php echo $computer->getInvoice(); ?></small>
                </h2>        
                <h2>Data Fattura:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getInvoiceDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?></small>
                </h2>   
                <hr class="devider devider-db-dotted">      
                <h2>Inserito il:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::SHORT, // time
                                "it_IT");
                        ?></small>
                </h2>          
                <h2>Ultima modifica:
                    <small><?php
                        echo $this->dateFormat(
                                $computer->getEditDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::SHORT, // time
                                "it_IT");
                        ?></small>
                </h2>                   
            </div>
            <!-- /.panel-body -->
        </div>        
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-clock-o fa-fw"></i> History
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Actions
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li>
                                <a href="<?php echo $this->url('computer/show',array('computerId' => $computer->getId(),'historyType' => 0)); ?>">
                                    Mostra tutti
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('computer/show',array('computerId' => $computer->getId(),'historyType' => 1)); ?>">
                                    Solo Creazione
                                </a>
                            </li>
                            <li class="active">
                                <a href="<?php echo $this->url('computer/show',array('computerId' => $computer->getId(),'historyType' => 2)); ?>">
                                    Solo modifica
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('computer/show',array('computerId' => $computer->getId(),'historyType' => 3)); ?>">
                                    Solo Assegnazione
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('computer/show',array('computerId' => $computer->getId(),'historyType' => 4)); ?>">
                                    Solo Cambio Stato
                                </a>
                            </li>                            
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->url('computer/clearhistory', array('computerId' => $computer->getId())); ?>"
                                   onclick="return confirm('<?php echo $this->translate('Really delete all computer history?') ?>')">
                                       <?php echo $this->translate('Clear history') ?>
                                </a> 
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <ul class="timeline">
                    <?php
                    $count = 0;
                    $history = $computer->getHistory($historyType);
                    foreach ($history as $row):
                        $count++;
                        $timelineClass = (($count % 2) == 0) ? 'timeline-inverted' : '';
                        $desc = $row->getAttributes()['description'];
                        ?>
                        <li class="<?php echo $timelineClass; ?>">
                            <div class="timeline-badge <?php echo $row->getAttributes()['class']; ?>"><i class="fa <?php echo $row->getAttributes()['icon']; ?>"></i>
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4 class="timeline-title"><?php echo $row->getAttributes()['action']; ?></h4>
                                    <p><small class="text-muted"><i class="fa fa-clock-o"></i> <?php
                                            echo $this->dateFormat(
                                                    $row->getEditDate(), IntlDateFormatter::LONG, // date
                                                    IntlDateFormatter::SHORT, // time
                                                    "it_IT");                                          
                                            ?> [<?php echo $row->getEditBy()->getDisplayName(); ?>]</small>
                                    </p>
                                </div>
                                <div class="timeline-body">
                                    <p>
                                        <?php echo $row->getAttributes()['description']; ?><br/>
                                    </p>
                                    <hr>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                                            <i class="fa fa-gear"></i>  <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" role="menu">
                                            <li>
                                                <a href="<?php echo $this->url('computer/history/edit', array('historyId' => $row->getId())); ?>">
                                                    <?php echo $this->translate('Edit') ?>
                                                </a>
                                            </li>
                                            <li>
                                                <a href="<?php echo $this->url('computer/history/remove', array('historyId' => $row->getId())); ?>"
                                                   onclick="return confirm('<?php echo $this->translate('Really delete history?') ?>')">
                                                       <?php echo $this->translate('Delete') ?>
                                                </a>                                            
                                            </li>
                                        </ul>
                                    </div>                                
                                </div>
                            </div>
                        </li>                    
                    <?php endforeach; ?>                    


                </ul>
            </div>
            <!-- /.panel-body -->
        </div>  
    </div>        
</div>    

<?php
echo $this->headLink()->prependStylesheet($this->basePath() . '/css/plugins/timeline.css');
