<?php echo $this->titleAndBread('Statistiche'); ?>
<?php $this->myFlashMessenger(); ?>   

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-bar-chart fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">1</div>
                        <div>Campioni evasi per mese</div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('samples/stats/stat1', array('year' => 0)); ?>">
                <div class="panel-footer">
                    <span class="pull-left">Mostra</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>



</div>

