<?php echo $this->titleAndBread('Aggiungi Allegati'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
/**
  echo $this->headLink()
  ->appendStylesheet($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css');
  echo $this->headScript()
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.min.js')
  ->prependFile($this->basePath() . '/assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput-angular.js');
 * 
 */
?>
<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

// Configure Errors Helper
$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<?php echo $this->form()->openTag($form); ?>
<fieldset>
    <legend><?php echo ($this->legend) ?: 'Files Upload' ?></legend>



    <?php
    $elem = $form->get('file');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php echo $errorClass ?>">
        <?php echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php echo $this->formFile($elem); ?>
            <?php echo $errorsHelper($elem); ?>
            <?php if (!empty($this->tempFiles)) { ?>
                <!--
                Note: You might not want to render the file input in this
                case either, depending on your use-case.
                -->
                <div class="help-block">
                    Uploaded: <ul>
                    <?php foreach ($this->tempFiles as $tempFile) { ?>
                        <li><?php echo $this->escapeHtml($tempFile['name']) ?></li>
                    <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>
    <?= $this->ztbFormElement($form->get('sample_id')); ?>
    <?= $this->ztbFormElement($form->get('type')); ?>

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Aggiungi</button>
        </div>
    </div>

</fieldset>
<?php echo $this->form()->closeTag($form); ?>
