<?php echo $this->titleAndBread('Allegati campionature'); ?>
<?php $this->myFlashMessenger(); ?>    
<div class="row">
    <div class="col-md-12">                
        Trovate <?php echo $totalRecord; ?> allegati
    </div>
</div>  

        
        <div class="row">
            <div class="col-md-12">
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('samples/attachments/search'));
                $form->setAttribute('class', 'navbar-form navbar-right');
                $form->prepare();

                echo $this->form()->openTag($form);
                echo $this->formSearch($form->get('search'));
                echo $this->formButton()->render($form->get('submit'), 'Go!');

                echo $this->form()->closeTag();
                ?>               
            </div>
        </div>


<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                </th>
                <th>
                    File Name
                </th>    
                <th>Campionatura</th>
                <th>Tipo</th>
                <th class="text-center"><i class="fa fa-calendar fa-fw"></i></th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->attachments as $attachment): ?>
                <tr>
                    <td class="cell cell-id">
                        <?php echo $attachment->getId(); ?>
                    </td>
                    <td class="cell">
                        <a href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                            <img class="img-responsive" style="max-height: 30px" src="/img/file-extension/<?php echo $attachment->getIcon(); ?>" alt="<?php echo $attachment->getFileName(); ?>" />
                        </a>
                    </td>                     
                    <td class="cell cell-serial">
                        <a href="<?php echo $attachmentPath . $attachment->getFileName(); ?>">
                            <?php echo $attachment->getFileName(); ?>
                        </a>
                    </td>         
                    <td class="cell">
                        <a href="<?php echo $this->url('samples/show', array('sampleId' => $attachment->getSample()->getId())); ?>">
                            <?php echo $attachment->getSample()->getId(); ?>
                        </a>
                    </td>    
                    <td class="cell">
                        <?php echo ucfirst($attachment->getAttachmentType()); ?>
                    </td>    
                    <td class="cell text-center">
                        <?php
                        echo $this->dateFormat(
                                $attachment->getCreatedDate(), IntlDateFormatter::LONG, // date
                                IntlDateFormatter::NONE, // time
                                "it_IT");
                        ?>                        
                    </td>                      
                    <td class="cell cell-ctrls text-center">
                        <a href="<?php echo $this->url('samples/attachments/remove', array('attachmentId' => $attachment->getId())); ?>"
                           class="btn btn-danger btn-xs emodal-confirm">
                            <span class="glyphicon glyphicon-remove"></span> Del
                        </a>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->attachments, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);
?>
