<?php echo $this->titleAndBread('Nuovo Fornitore'); ?>
<?php $this->myFlashMessenger(); ?>    

<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>
<div class="row">
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Nuovo fornitore
            </div>
            <div class="panel-body">
                <?= $this->ztbFormElement($form->get('companyName')); ?>
                <?= $this->ztbFormElement($form->get('status')); ?>
            </div>    
        </div>
    </div>    
</div>     
<div class="row">
    <div class = "col-md-6">
        
    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Aggiungi Fornitore</button>
            <a class="btn btn-default" href="javascript:history.back()"><i class="fa fa-mail-reply"></i> Indietro</a>
        </div>
    </div>        

    </div>
</div>  
