<?php echo $this->titleAndBread('Modifica fornitore'); ?>
<?php $this->myFlashMessenger(); ?>    
<?php
//$form->setAttribute('action', $this->url('application/default', array('controller' => 'index','action' => 'create')));
$form->setAttribute('action', $this->serverUrl(TRUE));
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'edit-form');
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="row">
    <div class = "col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Modifica fornitore
            </div>
            <div class="panel-body">
                <?= $this->ztbFormElement($form->get('companyName')); ?>
                <?= $this->ztbFormElement($form->get('status')); ?>
            </div>    
        </div>
    </div>    
</div>     
<div class="row">
    <div class = "col-md-6">
            <button class="btn btn-primary">Modifica Fornitore</button>
            <a class="btn btn-default" href="javascript:history.back()"><i class="fa fa-mail-reply"></i> Indietro</a>
    </div>
</div>    
<?php
echo $this->form()->closeTag();
?>
<?php
$this->headScript()->appendScript("
$(function() {

}); 
");


