<?php echo $this->titleAndBread('Fornitori'); ?>
<?php $this->myFlashMessenger(); ?>    

<div class="panel panel-default">
    <div class="panel-body">        
        <div class="row">
            <div class="col-md-6">                
                <strong>Trovati <?php echo $totalRecord; ?> fornitori</strong>
            </div>
            <div class="col-md-6 right" style="text-align: right">             
                <a href="<?php echo $this->url('application/suppliers/add') ?>" class="btn btn-primary">
                    <?php echo $this->translate('Aggiungi nuovo') ?>
                </a>           
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('application/suppliers/search'));
        $form->setAttribute('class', 'navbar-form navbar-right');
        $form->prepare();

        echo $this->form()->openTag($form);
        echo $this->formSearch($form->get('search'));
        echo $this->formButton()->render($form->get('submit'), 'Go!');

        echo $this->form()->closeTag();
        ?>               
    </div>
</div>


<div class="table-responsive">
    <table class="table table-bordered table-hover" id="example1">
        <thead>
            <tr>
                <th>Id</th>
                <th>Ragione Sociale</th>
                <th>Stato</th>    
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->suppliers as $supplier): ?>
                <tr>
                    <td class="cell cell-id">
                        <a href="<?php echo $this->url('application/suppliers/edit', array('suppliersId' => $supplier->getId())); ?>">
                            <?php echo $supplier->getId(); ?>
                        </a>
                    </td>                    
                    <td class="cell">
                        <?php echo $supplier->getCompanyName(); ?>
                    </td>                     
                    <td class="cell cell-serial">
                        <?php echo $supplier->getStatus(); ?>
                    </td>                             
                    <td class="cell cell-ctrls text-center">
                        <div class="btn-group">     

                            <a href="<?php echo $this->url('application/suppliers/edit', array('supplierId' => $supplier->getId())); ?>"
                               class="btn btn-info btn-xs">
                                <span class="glyphicon glyphicon-edit"></span> Edit
                            </a>
                            <!-- disabilitato per probabile "Integrity constraint violation"
                            <a href="<?php echo $this->url('application/suppliers/remove', array('supplierId' => $supplier->getId())); ?>"
                                   class="btn btn-danger btn-xs emodal-confirm">
                                <span class="glyphicon glyphicon-remove"></span> Del
                            </a>
                            -->

                        </div>                          
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $this->suppliers, 'Sliding', 'paginator-slide', array(
    'order_by' => $order_by,
    'order' => $order,
    'search_by' => $search_by,
    'pageAction' => $pageAction,
        )
);
?>
