<?php echo $this->titleAndBread('Dashboard', false); ?>
<?php $this->myFlashMessenger(); ?>   

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-laptop fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge"><?php echo $computerCount;  ?></div>
                        <div>Computers presenti!</div>
                    </div>
                </div>
            </div>
            <a href="<?php echo $this->url('computer/list'); ?>">
                <div class="panel-footer">
                    <span class="pull-left">Mostra</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">

    </div>
    <div class="col-lg-3 col-md-6">

    </div>

</div>


